// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"auroraride.com/edocseal/internal/ent/certification"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Certification is the model entity for the Certification schema.
type Certification struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 身份证号码
	IDCardNumber string `json:"id_card_number,omitempty"`
	// 私钥路径
	PrivatePath string `json:"private_path,omitempty"`
	// 证书路径
	CertPath string `json:"cert_path,omitempty"`
	// 证书过期时间
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// 证书生成方式
	Issuer       string `json:"issuer,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Certification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case certification.FieldID:
			values[i] = new(sql.NullInt64)
		case certification.FieldIDCardNumber, certification.FieldPrivatePath, certification.FieldCertPath, certification.FieldIssuer:
			values[i] = new(sql.NullString)
		case certification.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Certification fields.
func (_m *Certification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case certification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case certification.FieldIDCardNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id_card_number", values[i])
			} else if value.Valid {
				_m.IDCardNumber = value.String
			}
		case certification.FieldPrivatePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field private_path", values[i])
			} else if value.Valid {
				_m.PrivatePath = value.String
			}
		case certification.FieldCertPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cert_path", values[i])
			} else if value.Valid {
				_m.CertPath = value.String
			}
		case certification.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case certification.FieldIssuer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issuer", values[i])
			} else if value.Valid {
				_m.Issuer = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Certification.
// This includes values selected through modifiers, order, etc.
func (_m *Certification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Certification.
// Note that you need to call Certification.Unwrap() before calling this method if this Certification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Certification) Update() *CertificationUpdateOne {
	return NewCertificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Certification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Certification) Unwrap() *Certification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Certification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Certification) String() string {
	var builder strings.Builder
	builder.WriteString("Certification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("id_card_number=")
	builder.WriteString(_m.IDCardNumber)
	builder.WriteString(", ")
	builder.WriteString("private_path=")
	builder.WriteString(_m.PrivatePath)
	builder.WriteString(", ")
	builder.WriteString("cert_path=")
	builder.WriteString(_m.CertPath)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("issuer=")
	builder.WriteString(_m.Issuer)
	builder.WriteByte(')')
	return builder.String()
}

// Certifications is a parsable slice of Certification.
type Certifications []*Certification
