// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"auroraride.com/edocseal/internal/ent/document"
	"auroraride.com/edocseal/internal/model"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Document is the model entity for the Document schema.
type Document struct {
	config `json:"-"`
	// ID of the ent.
	// 文档ID
	ID string `json:"id,omitempty"`
	// 参数哈希
	Hash string `json:"hash,omitempty"`
	// 文档状态，文档超时后需删除
	Status document.Status `json:"status,omitempty"`
	// 模板ID
	TemplateID string `json:"template_id,omitempty"`
	// 身份证号码
	IDCardNumber string `json:"id_card_number,omitempty"`
	// 过期时间
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// 已签约短链接
	SignedURL string `json:"signed_url,omitempty"`
	// 已签约短链接
	UnsignedURL string `json:"unsigned_url,omitempty"`
	// 文档各项路径
	Paths *model.Paths `json:"paths,omitempty"`
	// 创建时间
	CreateAt     time.Time `json:"create_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Document) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case document.FieldPaths:
			values[i] = new([]byte)
		case document.FieldID, document.FieldHash, document.FieldStatus, document.FieldTemplateID, document.FieldIDCardNumber, document.FieldSignedURL, document.FieldUnsignedURL:
			values[i] = new(sql.NullString)
		case document.FieldExpiresAt, document.FieldCreateAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Document fields.
func (_m *Document) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case document.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case document.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				_m.Hash = value.String
			}
		case document.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = document.Status(value.String)
			}
		case document.FieldTemplateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = value.String
			}
		case document.FieldIDCardNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id_card_number", values[i])
			} else if value.Valid {
				_m.IDCardNumber = value.String
			}
		case document.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case document.FieldSignedURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signed_url", values[i])
			} else if value.Valid {
				_m.SignedURL = value.String
			}
		case document.FieldUnsignedURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unsigned_url", values[i])
			} else if value.Valid {
				_m.UnsignedURL = value.String
			}
		case document.FieldPaths:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field paths", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Paths); err != nil {
					return fmt.Errorf("unmarshal field paths: %w", err)
				}
			}
		case document.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				_m.CreateAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Document.
// This includes values selected through modifiers, order, etc.
func (_m *Document) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Document.
// Note that you need to call Document.Unwrap() before calling this method if this Document
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Document) Update() *DocumentUpdateOne {
	return NewDocumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Document entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Document) Unwrap() *Document {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Document is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Document) String() string {
	var builder strings.Builder
	builder.WriteString("Document(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("hash=")
	builder.WriteString(_m.Hash)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(_m.TemplateID)
	builder.WriteString(", ")
	builder.WriteString("id_card_number=")
	builder.WriteString(_m.IDCardNumber)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("signed_url=")
	builder.WriteString(_m.SignedURL)
	builder.WriteString(", ")
	builder.WriteString("unsigned_url=")
	builder.WriteString(_m.UnsignedURL)
	builder.WriteString(", ")
	builder.WriteString("paths=")
	builder.WriteString(fmt.Sprintf("%v", _m.Paths))
	builder.WriteString(", ")
	builder.WriteString("create_at=")
	builder.WriteString(_m.CreateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Documents is a parsable slice of Document.
type Documents []*Document
