// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"auroraride.com/edocseal/internal/ent/document"
	"auroraride.com/edocseal/internal/ent/predicate"
	"auroraride.com/edocseal/internal/model"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentUpdate is the builder for updating Document entities.
type DocumentUpdate struct {
	config
	hooks     []Hook
	mutation  *DocumentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DocumentUpdate builder.
func (_u *DocumentUpdate) Where(ps ...predicate.Document) *DocumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHash sets the "hash" field.
func (_u *DocumentUpdate) SetHash(v string) *DocumentUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableHash(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DocumentUpdate) SetStatus(v document.Status) *DocumentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableStatus(v *document.Status) *DocumentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *DocumentUpdate) SetTemplateID(v string) *DocumentUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableTemplateID(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetIDCardNumber sets the "id_card_number" field.
func (_u *DocumentUpdate) SetIDCardNumber(v string) *DocumentUpdate {
	_u.mutation.SetIDCardNumber(v)
	return _u
}

// SetNillableIDCardNumber sets the "id_card_number" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableIDCardNumber(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetIDCardNumber(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DocumentUpdate) SetExpiresAt(v time.Time) *DocumentUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableExpiresAt(v *time.Time) *DocumentUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetSignedURL sets the "signed_url" field.
func (_u *DocumentUpdate) SetSignedURL(v string) *DocumentUpdate {
	_u.mutation.SetSignedURL(v)
	return _u
}

// SetNillableSignedURL sets the "signed_url" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableSignedURL(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetSignedURL(*v)
	}
	return _u
}

// ClearSignedURL clears the value of the "signed_url" field.
func (_u *DocumentUpdate) ClearSignedURL() *DocumentUpdate {
	_u.mutation.ClearSignedURL()
	return _u
}

// SetUnsignedURL sets the "unsigned_url" field.
func (_u *DocumentUpdate) SetUnsignedURL(v string) *DocumentUpdate {
	_u.mutation.SetUnsignedURL(v)
	return _u
}

// SetNillableUnsignedURL sets the "unsigned_url" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableUnsignedURL(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetUnsignedURL(*v)
	}
	return _u
}

// ClearUnsignedURL clears the value of the "unsigned_url" field.
func (_u *DocumentUpdate) ClearUnsignedURL() *DocumentUpdate {
	_u.mutation.ClearUnsignedURL()
	return _u
}

// SetPaths sets the "paths" field.
func (_u *DocumentUpdate) SetPaths(v *model.Paths) *DocumentUpdate {
	_u.mutation.SetPaths(v)
	return _u
}

// SetCreateAt sets the "create_at" field.
func (_u *DocumentUpdate) SetCreateAt(v time.Time) *DocumentUpdate {
	_u.mutation.SetCreateAt(v)
	return _u
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableCreateAt(v *time.Time) *DocumentUpdate {
	if v != nil {
		_u.SetCreateAt(*v)
	}
	return _u
}

// Mutation returns the DocumentMutation object of the builder.
func (_u *DocumentUpdate) Mutation() *DocumentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := document.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Document.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IDCardNumber(); ok {
		if err := document.IDCardNumberValidator(v); err != nil {
			return &ValidationError{Name: "id_card_number", err: fmt.Errorf(`ent: validator failed for field "Document.id_card_number": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(document.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(document.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(document.FieldTemplateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IDCardNumber(); ok {
		_spec.SetField(document.FieldIDCardNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(document.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SignedURL(); ok {
		_spec.SetField(document.FieldSignedURL, field.TypeString, value)
	}
	if _u.mutation.SignedURLCleared() {
		_spec.ClearField(document.FieldSignedURL, field.TypeString)
	}
	if value, ok := _u.mutation.UnsignedURL(); ok {
		_spec.SetField(document.FieldUnsignedURL, field.TypeString, value)
	}
	if _u.mutation.UnsignedURLCleared() {
		_spec.ClearField(document.FieldUnsignedURL, field.TypeString)
	}
	if value, ok := _u.mutation.Paths(); ok {
		_spec.SetField(document.FieldPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreateAt(); ok {
		_spec.SetField(document.FieldCreateAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentUpdateOne is the builder for updating a single Document entity.
type DocumentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DocumentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetHash sets the "hash" field.
func (_u *DocumentUpdateOne) SetHash(v string) *DocumentUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableHash(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DocumentUpdateOne) SetStatus(v document.Status) *DocumentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableStatus(v *document.Status) *DocumentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *DocumentUpdateOne) SetTemplateID(v string) *DocumentUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableTemplateID(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetIDCardNumber sets the "id_card_number" field.
func (_u *DocumentUpdateOne) SetIDCardNumber(v string) *DocumentUpdateOne {
	_u.mutation.SetIDCardNumber(v)
	return _u
}

// SetNillableIDCardNumber sets the "id_card_number" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableIDCardNumber(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetIDCardNumber(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DocumentUpdateOne) SetExpiresAt(v time.Time) *DocumentUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableExpiresAt(v *time.Time) *DocumentUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetSignedURL sets the "signed_url" field.
func (_u *DocumentUpdateOne) SetSignedURL(v string) *DocumentUpdateOne {
	_u.mutation.SetSignedURL(v)
	return _u
}

// SetNillableSignedURL sets the "signed_url" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableSignedURL(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetSignedURL(*v)
	}
	return _u
}

// ClearSignedURL clears the value of the "signed_url" field.
func (_u *DocumentUpdateOne) ClearSignedURL() *DocumentUpdateOne {
	_u.mutation.ClearSignedURL()
	return _u
}

// SetUnsignedURL sets the "unsigned_url" field.
func (_u *DocumentUpdateOne) SetUnsignedURL(v string) *DocumentUpdateOne {
	_u.mutation.SetUnsignedURL(v)
	return _u
}

// SetNillableUnsignedURL sets the "unsigned_url" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableUnsignedURL(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetUnsignedURL(*v)
	}
	return _u
}

// ClearUnsignedURL clears the value of the "unsigned_url" field.
func (_u *DocumentUpdateOne) ClearUnsignedURL() *DocumentUpdateOne {
	_u.mutation.ClearUnsignedURL()
	return _u
}

// SetPaths sets the "paths" field.
func (_u *DocumentUpdateOne) SetPaths(v *model.Paths) *DocumentUpdateOne {
	_u.mutation.SetPaths(v)
	return _u
}

// SetCreateAt sets the "create_at" field.
func (_u *DocumentUpdateOne) SetCreateAt(v time.Time) *DocumentUpdateOne {
	_u.mutation.SetCreateAt(v)
	return _u
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableCreateAt(v *time.Time) *DocumentUpdateOne {
	if v != nil {
		_u.SetCreateAt(*v)
	}
	return _u
}

// Mutation returns the DocumentMutation object of the builder.
func (_u *DocumentUpdateOne) Mutation() *DocumentMutation {
	return _u.mutation
}

// Where appends a list predicates to the DocumentUpdate builder.
func (_u *DocumentUpdateOne) Where(ps ...predicate.Document) *DocumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentUpdateOne) Select(field string, fields ...string) *DocumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Document entity.
func (_u *DocumentUpdateOne) Save(ctx context.Context) (*Document, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentUpdateOne) SaveX(ctx context.Context) *Document {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := document.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Document.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IDCardNumber(); ok {
		if err := document.IDCardNumberValidator(v); err != nil {
			return &ValidationError{Name: "id_card_number", err: fmt.Errorf(`ent: validator failed for field "Document.id_card_number": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentUpdateOne) sqlSave(ctx context.Context) (_node *Document, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Document.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, document.FieldID)
		for _, f := range fields {
			if !document.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != document.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(document.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(document.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(document.FieldTemplateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IDCardNumber(); ok {
		_spec.SetField(document.FieldIDCardNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(document.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SignedURL(); ok {
		_spec.SetField(document.FieldSignedURL, field.TypeString, value)
	}
	if _u.mutation.SignedURLCleared() {
		_spec.ClearField(document.FieldSignedURL, field.TypeString)
	}
	if value, ok := _u.mutation.UnsignedURL(); ok {
		_spec.SetField(document.FieldUnsignedURL, field.TypeString, value)
	}
	if _u.mutation.UnsignedURLCleared() {
		_spec.ClearField(document.FieldUnsignedURL, field.TypeString)
	}
	if value, ok := _u.mutation.Paths(); ok {
		_spec.SetField(document.FieldPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreateAt(); ok {
		_spec.SetField(document.FieldCreateAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Document{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
