// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"auroraride.com/edocseal/internal/ent/enterprisecertification"
	"auroraride.com/edocseal/internal/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnterpriseCertificationDelete is the builder for deleting a EnterpriseCertification entity.
type EnterpriseCertificationDelete struct {
	config
	hooks    []Hook
	mutation *EnterpriseCertificationMutation
}

// Where appends a list predicates to the EnterpriseCertificationDelete builder.
func (_d *EnterpriseCertificationDelete) Where(ps ...predicate.EnterpriseCertification) *EnterpriseCertificationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EnterpriseCertificationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnterpriseCertificationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EnterpriseCertificationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(enterprisecertification.Table, sqlgraph.NewFieldSpec(enterprisecertification.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EnterpriseCertificationDeleteOne is the builder for deleting a single EnterpriseCertification entity.
type EnterpriseCertificationDeleteOne struct {
	_d *EnterpriseCertificationDelete
}

// Where appends a list predicates to the EnterpriseCertificationDelete builder.
func (_d *EnterpriseCertificationDeleteOne) Where(ps ...predicate.EnterpriseCertification) *EnterpriseCertificationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EnterpriseCertificationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enterprisecertification.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnterpriseCertificationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
