// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"auroraride.com/edocseal/internal/ent/enterprise"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnterpriseCreate is the builder for creating a Enterprise entity.
type EnterpriseCreate struct {
	config
	mutation *EnterpriseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreditCode sets the "credit_code" field.
func (_c *EnterpriseCreate) SetCreditCode(v string) *EnterpriseCreate {
	_c.mutation.SetCreditCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *EnterpriseCreate) SetName(v string) *EnterpriseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProvince sets the "province" field.
func (_c *EnterpriseCreate) SetProvince(v string) *EnterpriseCreate {
	_c.mutation.SetProvince(v)
	return _c
}

// SetCity sets the "city" field.
func (_c *EnterpriseCreate) SetCity(v string) *EnterpriseCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetPersonName sets the "person_name" field.
func (_c *EnterpriseCreate) SetPersonName(v string) *EnterpriseCreate {
	_c.mutation.SetPersonName(v)
	return _c
}

// SetNillablePersonName sets the "person_name" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillablePersonName(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetPersonName(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *EnterpriseCreate) SetPhone(v string) *EnterpriseCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillablePhone(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetIdcard sets the "idcard" field.
func (_c *EnterpriseCreate) SetIdcard(v string) *EnterpriseCreate {
	_c.mutation.SetIdcard(v)
	return _c
}

// SetNillableIdcard sets the "idcard" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableIdcard(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetIdcard(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *EnterpriseCreate) SetIsDefault(v bool) *EnterpriseCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableIsDefault(v *bool) *EnterpriseCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetRootCertPath sets the "root_cert_path" field.
func (_c *EnterpriseCreate) SetRootCertPath(v string) *EnterpriseCreate {
	_c.mutation.SetRootCertPath(v)
	return _c
}

// SetNillableRootCertPath sets the "root_cert_path" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableRootCertPath(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetRootCertPath(*v)
	}
	return _c
}

// SetRootPrivatePath sets the "root_private_path" field.
func (_c *EnterpriseCreate) SetRootPrivatePath(v string) *EnterpriseCreate {
	_c.mutation.SetRootPrivatePath(v)
	return _c
}

// SetNillableRootPrivatePath sets the "root_private_path" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableRootPrivatePath(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetRootPrivatePath(*v)
	}
	return _c
}

// SetRootExpiresAt sets the "root_expires_at" field.
func (_c *EnterpriseCreate) SetRootExpiresAt(v time.Time) *EnterpriseCreate {
	_c.mutation.SetRootExpiresAt(v)
	return _c
}

// SetNillableRootExpiresAt sets the "root_expires_at" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableRootExpiresAt(v *time.Time) *EnterpriseCreate {
	if v != nil {
		_c.SetRootExpiresAt(*v)
	}
	return _c
}

// Mutation returns the EnterpriseMutation object of the builder.
func (_c *EnterpriseCreate) Mutation() *EnterpriseMutation {
	return _c.mutation
}

// Save creates the Enterprise in the database.
func (_c *EnterpriseCreate) Save(ctx context.Context) (*Enterprise, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseCreate) SaveX(ctx context.Context) *Enterprise {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseCreate) defaults() {
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := enterprise.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseCreate) check() error {
	if _, ok := _c.mutation.CreditCode(); !ok {
		return &ValidationError{Name: "credit_code", err: errors.New(`ent: missing required field "Enterprise.credit_code"`)}
	}
	if v, ok := _c.mutation.CreditCode(); ok {
		if err := enterprise.CreditCodeValidator(v); err != nil {
			return &ValidationError{Name: "credit_code", err: fmt.Errorf(`ent: validator failed for field "Enterprise.credit_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Enterprise.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := enterprise.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Province(); !ok {
		return &ValidationError{Name: "province", err: errors.New(`ent: missing required field "Enterprise.province"`)}
	}
	if v, ok := _c.mutation.Province(); ok {
		if err := enterprise.ProvinceValidator(v); err != nil {
			return &ValidationError{Name: "province", err: fmt.Errorf(`ent: validator failed for field "Enterprise.province": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Enterprise.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := enterprise.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Enterprise.city": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PersonName(); ok {
		if err := enterprise.PersonNameValidator(v); err != nil {
			return &ValidationError{Name: "person_name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.person_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := enterprise.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Enterprise.phone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Idcard(); ok {
		if err := enterprise.IdcardValidator(v); err != nil {
			return &ValidationError{Name: "idcard", err: fmt.Errorf(`ent: validator failed for field "Enterprise.idcard": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "Enterprise.is_default"`)}
	}
	if v, ok := _c.mutation.RootCertPath(); ok {
		if err := enterprise.RootCertPathValidator(v); err != nil {
			return &ValidationError{Name: "root_cert_path", err: fmt.Errorf(`ent: validator failed for field "Enterprise.root_cert_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RootPrivatePath(); ok {
		if err := enterprise.RootPrivatePathValidator(v); err != nil {
			return &ValidationError{Name: "root_private_path", err: fmt.Errorf(`ent: validator failed for field "Enterprise.root_private_path": %w`, err)}
		}
	}
	return nil
}

func (_c *EnterpriseCreate) sqlSave(ctx context.Context) (*Enterprise, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseCreate) createSpec() (*Enterprise, *sqlgraph.CreateSpec) {
	var (
		_node = &Enterprise{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprise.Table, sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreditCode(); ok {
		_spec.SetField(enterprise.FieldCreditCode, field.TypeString, value)
		_node.CreditCode = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(enterprise.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Province(); ok {
		_spec.SetField(enterprise.FieldProvince, field.TypeString, value)
		_node.Province = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(enterprise.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.PersonName(); ok {
		_spec.SetField(enterprise.FieldPersonName, field.TypeString, value)
		_node.PersonName = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(enterprise.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Idcard(); ok {
		_spec.SetField(enterprise.FieldIdcard, field.TypeString, value)
		_node.Idcard = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(enterprise.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.RootCertPath(); ok {
		_spec.SetField(enterprise.FieldRootCertPath, field.TypeString, value)
		_node.RootCertPath = value
	}
	if value, ok := _c.mutation.RootPrivatePath(); ok {
		_spec.SetField(enterprise.FieldRootPrivatePath, field.TypeString, value)
		_node.RootPrivatePath = value
	}
	if value, ok := _c.mutation.RootExpiresAt(); ok {
		_spec.SetField(enterprise.FieldRootExpiresAt, field.TypeTime, value)
		_node.RootExpiresAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Enterprise.Create().
//		SetCreditCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseUpsert) {
//			SetCreditCode(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseUpsertOne {
	_c.conflict = opts
	return &EnterpriseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseCreate) OnConflictColumns(columns ...string) *EnterpriseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseUpsertOne is the builder for "upsert"-ing
	//  one Enterprise node.
	EnterpriseUpsertOne struct {
		create *EnterpriseCreate
	}

	// EnterpriseUpsert is the "OnConflict" setter.
	EnterpriseUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseUpsert) SetCreditCode(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldCreditCode, v)
	return u
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateCreditCode() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldCreditCode)
	return u
}

// SetName sets the "name" field.
func (u *EnterpriseUpsert) SetName(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateName() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldName)
	return u
}

// SetProvince sets the "province" field.
func (u *EnterpriseUpsert) SetProvince(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldProvince, v)
	return u
}

// UpdateProvince sets the "province" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateProvince() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldProvince)
	return u
}

// SetCity sets the "city" field.
func (u *EnterpriseUpsert) SetCity(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldCity, v)
	return u
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateCity() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldCity)
	return u
}

// SetPersonName sets the "person_name" field.
func (u *EnterpriseUpsert) SetPersonName(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldPersonName, v)
	return u
}

// UpdatePersonName sets the "person_name" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdatePersonName() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldPersonName)
	return u
}

// ClearPersonName clears the value of the "person_name" field.
func (u *EnterpriseUpsert) ClearPersonName() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldPersonName)
	return u
}

// SetPhone sets the "phone" field.
func (u *EnterpriseUpsert) SetPhone(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldPhone, v)
	return u
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdatePhone() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldPhone)
	return u
}

// ClearPhone clears the value of the "phone" field.
func (u *EnterpriseUpsert) ClearPhone() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldPhone)
	return u
}

// SetIdcard sets the "idcard" field.
func (u *EnterpriseUpsert) SetIdcard(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldIdcard, v)
	return u
}

// UpdateIdcard sets the "idcard" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateIdcard() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldIdcard)
	return u
}

// ClearIdcard clears the value of the "idcard" field.
func (u *EnterpriseUpsert) ClearIdcard() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldIdcard)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *EnterpriseUpsert) SetIsDefault(v bool) *EnterpriseUpsert {
	u.Set(enterprise.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateIsDefault() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldIsDefault)
	return u
}

// SetRootCertPath sets the "root_cert_path" field.
func (u *EnterpriseUpsert) SetRootCertPath(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldRootCertPath, v)
	return u
}

// UpdateRootCertPath sets the "root_cert_path" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateRootCertPath() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldRootCertPath)
	return u
}

// ClearRootCertPath clears the value of the "root_cert_path" field.
func (u *EnterpriseUpsert) ClearRootCertPath() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldRootCertPath)
	return u
}

// SetRootPrivatePath sets the "root_private_path" field.
func (u *EnterpriseUpsert) SetRootPrivatePath(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldRootPrivatePath, v)
	return u
}

// UpdateRootPrivatePath sets the "root_private_path" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateRootPrivatePath() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldRootPrivatePath)
	return u
}

// ClearRootPrivatePath clears the value of the "root_private_path" field.
func (u *EnterpriseUpsert) ClearRootPrivatePath() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldRootPrivatePath)
	return u
}

// SetRootExpiresAt sets the "root_expires_at" field.
func (u *EnterpriseUpsert) SetRootExpiresAt(v time.Time) *EnterpriseUpsert {
	u.Set(enterprise.FieldRootExpiresAt, v)
	return u
}

// UpdateRootExpiresAt sets the "root_expires_at" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateRootExpiresAt() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldRootExpiresAt)
	return u
}

// ClearRootExpiresAt clears the value of the "root_expires_at" field.
func (u *EnterpriseUpsert) ClearRootExpiresAt() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldRootExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseUpsertOne) UpdateNewValues() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseUpsertOne) Ignore() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseUpsertOne) DoNothing() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseCreate.OnConflict
// documentation for more info.
func (u *EnterpriseUpsertOne) Update(set func(*EnterpriseUpsert)) *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseUpsertOne) SetCreditCode(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetCreditCode(v)
	})
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateCreditCode() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateCreditCode()
	})
}

// SetName sets the "name" field.
func (u *EnterpriseUpsertOne) SetName(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateName() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateName()
	})
}

// SetProvince sets the "province" field.
func (u *EnterpriseUpsertOne) SetProvince(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetProvince(v)
	})
}

// UpdateProvince sets the "province" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateProvince() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateProvince()
	})
}

// SetCity sets the "city" field.
func (u *EnterpriseUpsertOne) SetCity(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateCity() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateCity()
	})
}

// SetPersonName sets the "person_name" field.
func (u *EnterpriseUpsertOne) SetPersonName(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetPersonName(v)
	})
}

// UpdatePersonName sets the "person_name" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdatePersonName() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdatePersonName()
	})
}

// ClearPersonName clears the value of the "person_name" field.
func (u *EnterpriseUpsertOne) ClearPersonName() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearPersonName()
	})
}

// SetPhone sets the "phone" field.
func (u *EnterpriseUpsertOne) SetPhone(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdatePhone() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *EnterpriseUpsertOne) ClearPhone() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearPhone()
	})
}

// SetIdcard sets the "idcard" field.
func (u *EnterpriseUpsertOne) SetIdcard(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetIdcard(v)
	})
}

// UpdateIdcard sets the "idcard" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateIdcard() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateIdcard()
	})
}

// ClearIdcard clears the value of the "idcard" field.
func (u *EnterpriseUpsertOne) ClearIdcard() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearIdcard()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *EnterpriseUpsertOne) SetIsDefault(v bool) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateIsDefault() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateIsDefault()
	})
}

// SetRootCertPath sets the "root_cert_path" field.
func (u *EnterpriseUpsertOne) SetRootCertPath(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetRootCertPath(v)
	})
}

// UpdateRootCertPath sets the "root_cert_path" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateRootCertPath() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateRootCertPath()
	})
}

// ClearRootCertPath clears the value of the "root_cert_path" field.
func (u *EnterpriseUpsertOne) ClearRootCertPath() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearRootCertPath()
	})
}

// SetRootPrivatePath sets the "root_private_path" field.
func (u *EnterpriseUpsertOne) SetRootPrivatePath(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetRootPrivatePath(v)
	})
}

// UpdateRootPrivatePath sets the "root_private_path" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateRootPrivatePath() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateRootPrivatePath()
	})
}

// ClearRootPrivatePath clears the value of the "root_private_path" field.
func (u *EnterpriseUpsertOne) ClearRootPrivatePath() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearRootPrivatePath()
	})
}

// SetRootExpiresAt sets the "root_expires_at" field.
func (u *EnterpriseUpsertOne) SetRootExpiresAt(v time.Time) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetRootExpiresAt(v)
	})
}

// UpdateRootExpiresAt sets the "root_expires_at" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateRootExpiresAt() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateRootExpiresAt()
	})
}

// ClearRootExpiresAt clears the value of the "root_expires_at" field.
func (u *EnterpriseUpsertOne) ClearRootExpiresAt() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearRootExpiresAt()
	})
}

// Exec executes the query.
func (u *EnterpriseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Save creates the Enterprise in the database.
func (u *EnterpriseUpsertOne) Save(ctx context.Context) (*Enterprise, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for EnterpriseCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

// EnterpriseCreateBulk is the builder for creating many Enterprise entities in bulk.
type EnterpriseCreateBulk struct {
	config
	err      error
	builders []*EnterpriseCreate
	conflict []sql.ConflictOption
}

// Save creates the Enterprise entities in the database.
func (_c *EnterpriseCreateBulk) Save(ctx context.Context) ([]*Enterprise, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Enterprise, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseCreateBulk) SaveX(ctx context.Context) []*Enterprise {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Enterprise.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseUpsert) {
//			SetCreditCode(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseUpsertBulk {
	_c.conflict = opts
	return &EnterpriseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseCreateBulk) OnConflictColumns(columns ...string) *EnterpriseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseUpsertBulk{
		create: _c,
	}
}

// EnterpriseUpsertBulk is the builder for "upsert"-ing
// a bulk of Enterprise nodes.
type EnterpriseUpsertBulk struct {
	create *EnterpriseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseUpsertBulk) UpdateNewValues() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseUpsertBulk) Ignore() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseUpsertBulk) DoNothing() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseUpsertBulk) Update(set func(*EnterpriseUpsert)) *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseUpsertBulk) SetCreditCode(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetCreditCode(v)
	})
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateCreditCode() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateCreditCode()
	})
}

// SetName sets the "name" field.
func (u *EnterpriseUpsertBulk) SetName(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateName() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateName()
	})
}

// SetProvince sets the "province" field.
func (u *EnterpriseUpsertBulk) SetProvince(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetProvince(v)
	})
}

// UpdateProvince sets the "province" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateProvince() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateProvince()
	})
}

// SetCity sets the "city" field.
func (u *EnterpriseUpsertBulk) SetCity(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateCity() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateCity()
	})
}

// SetPersonName sets the "person_name" field.
func (u *EnterpriseUpsertBulk) SetPersonName(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetPersonName(v)
	})
}

// UpdatePersonName sets the "person_name" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdatePersonName() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdatePersonName()
	})
}

// ClearPersonName clears the value of the "person_name" field.
func (u *EnterpriseUpsertBulk) ClearPersonName() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearPersonName()
	})
}

// SetPhone sets the "phone" field.
func (u *EnterpriseUpsertBulk) SetPhone(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdatePhone() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *EnterpriseUpsertBulk) ClearPhone() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearPhone()
	})
}

// SetIdcard sets the "idcard" field.
func (u *EnterpriseUpsertBulk) SetIdcard(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetIdcard(v)
	})
}

// UpdateIdcard sets the "idcard" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateIdcard() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateIdcard()
	})
}

// ClearIdcard clears the value of the "idcard" field.
func (u *EnterpriseUpsertBulk) ClearIdcard() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearIdcard()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *EnterpriseUpsertBulk) SetIsDefault(v bool) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateIsDefault() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateIsDefault()
	})
}

// SetRootCertPath sets the "root_cert_path" field.
func (u *EnterpriseUpsertBulk) SetRootCertPath(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetRootCertPath(v)
	})
}

// UpdateRootCertPath sets the "root_cert_path" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateRootCertPath() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateRootCertPath()
	})
}

// ClearRootCertPath clears the value of the "root_cert_path" field.
func (u *EnterpriseUpsertBulk) ClearRootCertPath() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearRootCertPath()
	})
}

// SetRootPrivatePath sets the "root_private_path" field.
func (u *EnterpriseUpsertBulk) SetRootPrivatePath(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetRootPrivatePath(v)
	})
}

// UpdateRootPrivatePath sets the "root_private_path" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateRootPrivatePath() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateRootPrivatePath()
	})
}

// ClearRootPrivatePath clears the value of the "root_private_path" field.
func (u *EnterpriseUpsertBulk) ClearRootPrivatePath() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearRootPrivatePath()
	})
}

// SetRootExpiresAt sets the "root_expires_at" field.
func (u *EnterpriseUpsertBulk) SetRootExpiresAt(v time.Time) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetRootExpiresAt(v)
	})
}

// UpdateRootExpiresAt sets the "root_expires_at" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateRootExpiresAt() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateRootExpiresAt()
	})
}

// ClearRootExpiresAt clears the value of the "root_expires_at" field.
func (u *EnterpriseUpsertBulk) ClearRootExpiresAt() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearRootExpiresAt()
	})
}

// Exec executes the query.
func (u *EnterpriseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
