// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"auroraride.com/edocseal/internal/ent/enterprisecertification"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnterpriseCertificationCreate is the builder for creating a EnterpriseCertification entity.
type EnterpriseCertificationCreate struct {
	config
	mutation *EnterpriseCertificationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreditCode sets the "credit_code" field.
func (_c *EnterpriseCertificationCreate) SetCreditCode(v string) *EnterpriseCertificationCreate {
	_c.mutation.SetCreditCode(v)
	return _c
}

// SetIssuer sets the "issuer" field.
func (_c *EnterpriseCertificationCreate) SetIssuer(v string) *EnterpriseCertificationCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetPrivatePath sets the "private_path" field.
func (_c *EnterpriseCertificationCreate) SetPrivatePath(v string) *EnterpriseCertificationCreate {
	_c.mutation.SetPrivatePath(v)
	return _c
}

// SetCertPath sets the "cert_path" field.
func (_c *EnterpriseCertificationCreate) SetCertPath(v string) *EnterpriseCertificationCreate {
	_c.mutation.SetCertPath(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EnterpriseCertificationCreate) SetExpiresAt(v time.Time) *EnterpriseCertificationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the EnterpriseCertificationMutation object of the builder.
func (_c *EnterpriseCertificationCreate) Mutation() *EnterpriseCertificationMutation {
	return _c.mutation
}

// Save creates the EnterpriseCertification in the database.
func (_c *EnterpriseCertificationCreate) Save(ctx context.Context) (*EnterpriseCertification, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseCertificationCreate) SaveX(ctx context.Context) *EnterpriseCertification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseCertificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseCertificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseCertificationCreate) check() error {
	if _, ok := _c.mutation.CreditCode(); !ok {
		return &ValidationError{Name: "credit_code", err: errors.New(`ent: missing required field "EnterpriseCertification.credit_code"`)}
	}
	if v, ok := _c.mutation.CreditCode(); ok {
		if err := enterprisecertification.CreditCodeValidator(v); err != nil {
			return &ValidationError{Name: "credit_code", err: fmt.Errorf(`ent: validator failed for field "EnterpriseCertification.credit_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "EnterpriseCertification.issuer"`)}
	}
	if v, ok := _c.mutation.Issuer(); ok {
		if err := enterprisecertification.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "EnterpriseCertification.issuer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrivatePath(); !ok {
		return &ValidationError{Name: "private_path", err: errors.New(`ent: missing required field "EnterpriseCertification.private_path"`)}
	}
	if v, ok := _c.mutation.PrivatePath(); ok {
		if err := enterprisecertification.PrivatePathValidator(v); err != nil {
			return &ValidationError{Name: "private_path", err: fmt.Errorf(`ent: validator failed for field "EnterpriseCertification.private_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CertPath(); !ok {
		return &ValidationError{Name: "cert_path", err: errors.New(`ent: missing required field "EnterpriseCertification.cert_path"`)}
	}
	if v, ok := _c.mutation.CertPath(); ok {
		if err := enterprisecertification.CertPathValidator(v); err != nil {
			return &ValidationError{Name: "cert_path", err: fmt.Errorf(`ent: validator failed for field "EnterpriseCertification.cert_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "EnterpriseCertification.expires_at"`)}
	}
	return nil
}

func (_c *EnterpriseCertificationCreate) sqlSave(ctx context.Context) (*EnterpriseCertification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseCertificationCreate) createSpec() (*EnterpriseCertification, *sqlgraph.CreateSpec) {
	var (
		_node = &EnterpriseCertification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprisecertification.Table, sqlgraph.NewFieldSpec(enterprisecertification.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreditCode(); ok {
		_spec.SetField(enterprisecertification.FieldCreditCode, field.TypeString, value)
		_node.CreditCode = value
	}
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(enterprisecertification.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := _c.mutation.PrivatePath(); ok {
		_spec.SetField(enterprisecertification.FieldPrivatePath, field.TypeString, value)
		_node.PrivatePath = value
	}
	if value, ok := _c.mutation.CertPath(); ok {
		_spec.SetField(enterprisecertification.FieldCertPath, field.TypeString, value)
		_node.CertPath = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(enterprisecertification.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseCertification.Create().
//		SetCreditCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseCertificationUpsert) {
//			SetCreditCode(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseCertificationCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseCertificationUpsertOne {
	_c.conflict = opts
	return &EnterpriseCertificationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseCertification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseCertificationCreate) OnConflictColumns(columns ...string) *EnterpriseCertificationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseCertificationUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseCertificationUpsertOne is the builder for "upsert"-ing
	//  one EnterpriseCertification node.
	EnterpriseCertificationUpsertOne struct {
		create *EnterpriseCertificationCreate
	}

	// EnterpriseCertificationUpsert is the "OnConflict" setter.
	EnterpriseCertificationUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseCertificationUpsert) SetCreditCode(v string) *EnterpriseCertificationUpsert {
	u.Set(enterprisecertification.FieldCreditCode, v)
	return u
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsert) UpdateCreditCode() *EnterpriseCertificationUpsert {
	u.SetExcluded(enterprisecertification.FieldCreditCode)
	return u
}

// SetIssuer sets the "issuer" field.
func (u *EnterpriseCertificationUpsert) SetIssuer(v string) *EnterpriseCertificationUpsert {
	u.Set(enterprisecertification.FieldIssuer, v)
	return u
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsert) UpdateIssuer() *EnterpriseCertificationUpsert {
	u.SetExcluded(enterprisecertification.FieldIssuer)
	return u
}

// SetPrivatePath sets the "private_path" field.
func (u *EnterpriseCertificationUpsert) SetPrivatePath(v string) *EnterpriseCertificationUpsert {
	u.Set(enterprisecertification.FieldPrivatePath, v)
	return u
}

// UpdatePrivatePath sets the "private_path" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsert) UpdatePrivatePath() *EnterpriseCertificationUpsert {
	u.SetExcluded(enterprisecertification.FieldPrivatePath)
	return u
}

// SetCertPath sets the "cert_path" field.
func (u *EnterpriseCertificationUpsert) SetCertPath(v string) *EnterpriseCertificationUpsert {
	u.Set(enterprisecertification.FieldCertPath, v)
	return u
}

// UpdateCertPath sets the "cert_path" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsert) UpdateCertPath() *EnterpriseCertificationUpsert {
	u.SetExcluded(enterprisecertification.FieldCertPath)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *EnterpriseCertificationUpsert) SetExpiresAt(v time.Time) *EnterpriseCertificationUpsert {
	u.Set(enterprisecertification.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsert) UpdateExpiresAt() *EnterpriseCertificationUpsert {
	u.SetExcluded(enterprisecertification.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnterpriseCertification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseCertificationUpsertOne) UpdateNewValues() *EnterpriseCertificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseCertification.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseCertificationUpsertOne) Ignore() *EnterpriseCertificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseCertificationUpsertOne) DoNothing() *EnterpriseCertificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseCertificationCreate.OnConflict
// documentation for more info.
func (u *EnterpriseCertificationUpsertOne) Update(set func(*EnterpriseCertificationUpsert)) *EnterpriseCertificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseCertificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseCertificationUpsertOne) SetCreditCode(v string) *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetCreditCode(v)
	})
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertOne) UpdateCreditCode() *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdateCreditCode()
	})
}

// SetIssuer sets the "issuer" field.
func (u *EnterpriseCertificationUpsertOne) SetIssuer(v string) *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertOne) UpdateIssuer() *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdateIssuer()
	})
}

// SetPrivatePath sets the "private_path" field.
func (u *EnterpriseCertificationUpsertOne) SetPrivatePath(v string) *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetPrivatePath(v)
	})
}

// UpdatePrivatePath sets the "private_path" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertOne) UpdatePrivatePath() *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdatePrivatePath()
	})
}

// SetCertPath sets the "cert_path" field.
func (u *EnterpriseCertificationUpsertOne) SetCertPath(v string) *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetCertPath(v)
	})
}

// UpdateCertPath sets the "cert_path" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertOne) UpdateCertPath() *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdateCertPath()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EnterpriseCertificationUpsertOne) SetExpiresAt(v time.Time) *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertOne) UpdateExpiresAt() *EnterpriseCertificationUpsertOne {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *EnterpriseCertificationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseCertificationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseCertificationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseCertificationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseCertificationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Save creates the EnterpriseCertification in the database.
func (u *EnterpriseCertificationUpsertOne) Save(ctx context.Context) (*EnterpriseCertification, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for EnterpriseCertificationCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

// EnterpriseCertificationCreateBulk is the builder for creating many EnterpriseCertification entities in bulk.
type EnterpriseCertificationCreateBulk struct {
	config
	err      error
	builders []*EnterpriseCertificationCreate
	conflict []sql.ConflictOption
}

// Save creates the EnterpriseCertification entities in the database.
func (_c *EnterpriseCertificationCreateBulk) Save(ctx context.Context) ([]*EnterpriseCertification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnterpriseCertification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseCertificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseCertificationCreateBulk) SaveX(ctx context.Context) []*EnterpriseCertification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseCertificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseCertificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseCertification.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseCertificationUpsert) {
//			SetCreditCode(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseCertificationCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseCertificationUpsertBulk {
	_c.conflict = opts
	return &EnterpriseCertificationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseCertification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseCertificationCreateBulk) OnConflictColumns(columns ...string) *EnterpriseCertificationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseCertificationUpsertBulk{
		create: _c,
	}
}

// EnterpriseCertificationUpsertBulk is the builder for "upsert"-ing
// a bulk of EnterpriseCertification nodes.
type EnterpriseCertificationUpsertBulk struct {
	create *EnterpriseCertificationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnterpriseCertification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseCertificationUpsertBulk) UpdateNewValues() *EnterpriseCertificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseCertification.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseCertificationUpsertBulk) Ignore() *EnterpriseCertificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseCertificationUpsertBulk) DoNothing() *EnterpriseCertificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseCertificationCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseCertificationUpsertBulk) Update(set func(*EnterpriseCertificationUpsert)) *EnterpriseCertificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseCertificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseCertificationUpsertBulk) SetCreditCode(v string) *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetCreditCode(v)
	})
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertBulk) UpdateCreditCode() *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdateCreditCode()
	})
}

// SetIssuer sets the "issuer" field.
func (u *EnterpriseCertificationUpsertBulk) SetIssuer(v string) *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertBulk) UpdateIssuer() *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdateIssuer()
	})
}

// SetPrivatePath sets the "private_path" field.
func (u *EnterpriseCertificationUpsertBulk) SetPrivatePath(v string) *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetPrivatePath(v)
	})
}

// UpdatePrivatePath sets the "private_path" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertBulk) UpdatePrivatePath() *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdatePrivatePath()
	})
}

// SetCertPath sets the "cert_path" field.
func (u *EnterpriseCertificationUpsertBulk) SetCertPath(v string) *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetCertPath(v)
	})
}

// UpdateCertPath sets the "cert_path" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertBulk) UpdateCertPath() *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdateCertPath()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EnterpriseCertificationUpsertBulk) SetExpiresAt(v time.Time) *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EnterpriseCertificationUpsertBulk) UpdateExpiresAt() *EnterpriseCertificationUpsertBulk {
	return u.Update(func(s *EnterpriseCertificationUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *EnterpriseCertificationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseCertificationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseCertificationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseCertificationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
