// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"auroraride.com/edocseal/internal/ent/enterprise"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Enterprise is the model entity for the Enterprise schema.
type Enterprise struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 统一社会信用代码
	CreditCode string `json:"credit_code,omitempty"`
	// 企业名称
	Name string `json:"name,omitempty"`
	// 省份
	Province string `json:"province,omitempty"`
	// 城市
	City string `json:"city,omitempty"`
	// 代办人姓名，向陕西CA 申请证书时使用
	PersonName string `json:"person_name,omitempty"`
	// 代办人手机号，向陕西CA 申请证书时使用
	Phone string `json:"phone,omitempty"`
	// 代办人身份证号，向陕西CA 申请证书时使用
	Idcard string `json:"idcard,omitempty"`
	// 是否为当前签约企业
	IsDefault bool `json:"is_default,omitempty"`
	// 自签根证书路径
	RootCertPath string `json:"root_cert_path,omitempty"`
	// 自签根证书私钥路径
	RootPrivatePath string `json:"root_private_path,omitempty"`
	// 自签根证书过期时间
	RootExpiresAt *time.Time `json:"root_expires_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Enterprise) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case enterprise.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case enterprise.FieldID:
			values[i] = new(sql.NullInt64)
		case enterprise.FieldCreditCode, enterprise.FieldName, enterprise.FieldProvince, enterprise.FieldCity, enterprise.FieldPersonName, enterprise.FieldPhone, enterprise.FieldIdcard, enterprise.FieldRootCertPath, enterprise.FieldRootPrivatePath:
			values[i] = new(sql.NullString)
		case enterprise.FieldRootExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Enterprise fields.
func (_m *Enterprise) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case enterprise.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case enterprise.FieldCreditCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credit_code", values[i])
			} else if value.Valid {
				_m.CreditCode = value.String
			}
		case enterprise.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case enterprise.FieldProvince:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field province", values[i])
			} else if value.Valid {
				_m.Province = value.String
			}
		case enterprise.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				_m.City = value.String
			}
		case enterprise.FieldPersonName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field person_name", values[i])
			} else if value.Valid {
				_m.PersonName = value.String
			}
		case enterprise.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case enterprise.FieldIdcard:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idcard", values[i])
			} else if value.Valid {
				_m.Idcard = value.String
			}
		case enterprise.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case enterprise.FieldRootCertPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field root_cert_path", values[i])
			} else if value.Valid {
				_m.RootCertPath = value.String
			}
		case enterprise.FieldRootPrivatePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field root_private_path", values[i])
			} else if value.Valid {
				_m.RootPrivatePath = value.String
			}
		case enterprise.FieldRootExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field root_expires_at", values[i])
			} else if value.Valid {
				_m.RootExpiresAt = new(time.Time)
				*_m.RootExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Enterprise.
// This includes values selected through modifiers, order, etc.
func (_m *Enterprise) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Enterprise.
// Note that you need to call Enterprise.Unwrap() before calling this method if this Enterprise
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Enterprise) Update() *EnterpriseUpdateOne {
	return NewEnterpriseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Enterprise entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Enterprise) Unwrap() *Enterprise {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Enterprise is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Enterprise) String() string {
	var builder strings.Builder
	builder.WriteString("Enterprise(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("credit_code=")
	builder.WriteString(_m.CreditCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("province=")
	builder.WriteString(_m.Province)
	builder.WriteString(", ")
	builder.WriteString("city=")
	builder.WriteString(_m.City)
	builder.WriteString(", ")
	builder.WriteString("person_name=")
	builder.WriteString(_m.PersonName)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("idcard=")
	builder.WriteString(_m.Idcard)
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("root_cert_path=")
	builder.WriteString(_m.RootCertPath)
	builder.WriteString(", ")
	builder.WriteString("root_private_path=")
	builder.WriteString(_m.RootPrivatePath)
	builder.WriteString(", ")
	if v := _m.RootExpiresAt; v != nil {
		builder.WriteString("root_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Enterprises is a parsable slice of Enterprise.
type Enterprises []*Enterprise
