// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"auroraride.com/edocseal/internal/ent/enterprise"
	"auroraride.com/edocseal/internal/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnterpriseDelete is the builder for deleting a Enterprise entity.
type EnterpriseDelete struct {
	config
	hooks    []Hook
	mutation *EnterpriseMutation
}

// Where appends a list predicates to the EnterpriseDelete builder.
func (_d *EnterpriseDelete) Where(ps ...predicate.Enterprise) *EnterpriseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EnterpriseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnterpriseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EnterpriseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(enterprise.Table, sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EnterpriseDeleteOne is the builder for deleting a single Enterprise entity.
type EnterpriseDeleteOne struct {
	_d *EnterpriseDelete
}

// Where appends a list predicates to the EnterpriseDelete builder.
func (_d *EnterpriseDeleteOne) Where(ps ...predicate.Enterprise) *EnterpriseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EnterpriseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enterprise.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnterpriseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
