// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"auroraride.com/edocseal/internal/ent/certification"
	"auroraride.com/edocseal/internal/ent/document"
	"auroraride.com/edocseal/internal/ent/enterprise"
	"auroraride.com/edocseal/internal/ent/enterprisecertification"
	"auroraride.com/edocseal/internal/ent/predicate"
	"auroraride.com/edocseal/internal/model"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCertification           = "Certification"
	TypeDocument                = "Document"
	TypeEnterprise              = "Enterprise"
	TypeEnterpriseCertification = "EnterpriseCertification"
)

// CertificationMutation represents an operation that mutates the Certification nodes in the graph.
type CertificationMutation struct {
	config
	op             Op
	typ            string
	id             *int
	id_card_number *string
	private_path   *string
	cert_path      *string
	expires_at     *time.Time
	issuer         *string
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*Certification, error)
	predicates     []predicate.Certification
}

var _ ent.Mutation = (*CertificationMutation)(nil)

// certificationOption allows management of the mutation configuration using functional options.
type certificationOption func(*CertificationMutation)

// newCertificationMutation creates new mutation for the Certification entity.
func newCertificationMutation(c config, op Op, opts ...certificationOption) *CertificationMutation {
	m := &CertificationMutation{
		config:        c,
		op:            op,
		typ:           TypeCertification,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCertificationID sets the ID field of the mutation.
func withCertificationID(id int) certificationOption {
	return func(m *CertificationMutation) {
		var (
			err   error
			once  sync.Once
			value *Certification
		)
		m.oldValue = func(ctx context.Context) (*Certification, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Certification.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCertification sets the old Certification of the mutation.
func withCertification(node *Certification) certificationOption {
	return func(m *CertificationMutation) {
		m.oldValue = func(context.Context) (*Certification, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CertificationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CertificationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CertificationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CertificationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Certification.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetIDCardNumber sets the "id_card_number" field.
func (m *CertificationMutation) SetIDCardNumber(s string) {
	m.id_card_number = &s
}

// IDCardNumber returns the value of the "id_card_number" field in the mutation.
func (m *CertificationMutation) IDCardNumber() (r string, exists bool) {
	v := m.id_card_number
	if v == nil {
		return
	}
	return *v, true
}

// OldIDCardNumber returns the old "id_card_number" field's value of the Certification entity.
// If the Certification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificationMutation) OldIDCardNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIDCardNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIDCardNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIDCardNumber: %w", err)
	}
	return oldValue.IDCardNumber, nil
}

// ResetIDCardNumber resets all changes to the "id_card_number" field.
func (m *CertificationMutation) ResetIDCardNumber() {
	m.id_card_number = nil
}

// SetPrivatePath sets the "private_path" field.
func (m *CertificationMutation) SetPrivatePath(s string) {
	m.private_path = &s
}

// PrivatePath returns the value of the "private_path" field in the mutation.
func (m *CertificationMutation) PrivatePath() (r string, exists bool) {
	v := m.private_path
	if v == nil {
		return
	}
	return *v, true
}

// OldPrivatePath returns the old "private_path" field's value of the Certification entity.
// If the Certification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificationMutation) OldPrivatePath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrivatePath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrivatePath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrivatePath: %w", err)
	}
	return oldValue.PrivatePath, nil
}

// ResetPrivatePath resets all changes to the "private_path" field.
func (m *CertificationMutation) ResetPrivatePath() {
	m.private_path = nil
}

// SetCertPath sets the "cert_path" field.
func (m *CertificationMutation) SetCertPath(s string) {
	m.cert_path = &s
}

// CertPath returns the value of the "cert_path" field in the mutation.
func (m *CertificationMutation) CertPath() (r string, exists bool) {
	v := m.cert_path
	if v == nil {
		return
	}
	return *v, true
}

// OldCertPath returns the old "cert_path" field's value of the Certification entity.
// If the Certification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificationMutation) OldCertPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCertPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCertPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCertPath: %w", err)
	}
	return oldValue.CertPath, nil
}

// ResetCertPath resets all changes to the "cert_path" field.
func (m *CertificationMutation) ResetCertPath() {
	m.cert_path = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *CertificationMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *CertificationMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the Certification entity.
// If the Certification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificationMutation) OldExpiresAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *CertificationMutation) ResetExpiresAt() {
	m.expires_at = nil
}

// SetIssuer sets the "issuer" field.
func (m *CertificationMutation) SetIssuer(s string) {
	m.issuer = &s
}

// Issuer returns the value of the "issuer" field in the mutation.
func (m *CertificationMutation) Issuer() (r string, exists bool) {
	v := m.issuer
	if v == nil {
		return
	}
	return *v, true
}

// OldIssuer returns the old "issuer" field's value of the Certification entity.
// If the Certification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CertificationMutation) OldIssuer(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIssuer is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIssuer requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIssuer: %w", err)
	}
	return oldValue.Issuer, nil
}

// ResetIssuer resets all changes to the "issuer" field.
func (m *CertificationMutation) ResetIssuer() {
	m.issuer = nil
}

// Where appends a list predicates to the CertificationMutation builder.
func (m *CertificationMutation) Where(ps ...predicate.Certification) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CertificationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CertificationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Certification, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CertificationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CertificationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Certification).
func (m *CertificationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CertificationMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.id_card_number != nil {
		fields = append(fields, certification.FieldIDCardNumber)
	}
	if m.private_path != nil {
		fields = append(fields, certification.FieldPrivatePath)
	}
	if m.cert_path != nil {
		fields = append(fields, certification.FieldCertPath)
	}
	if m.expires_at != nil {
		fields = append(fields, certification.FieldExpiresAt)
	}
	if m.issuer != nil {
		fields = append(fields, certification.FieldIssuer)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CertificationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case certification.FieldIDCardNumber:
		return m.IDCardNumber()
	case certification.FieldPrivatePath:
		return m.PrivatePath()
	case certification.FieldCertPath:
		return m.CertPath()
	case certification.FieldExpiresAt:
		return m.ExpiresAt()
	case certification.FieldIssuer:
		return m.Issuer()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CertificationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case certification.FieldIDCardNumber:
		return m.OldIDCardNumber(ctx)
	case certification.FieldPrivatePath:
		return m.OldPrivatePath(ctx)
	case certification.FieldCertPath:
		return m.OldCertPath(ctx)
	case certification.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case certification.FieldIssuer:
		return m.OldIssuer(ctx)
	}
	return nil, fmt.Errorf("unknown Certification field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CertificationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case certification.FieldIDCardNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIDCardNumber(v)
		return nil
	case certification.FieldPrivatePath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrivatePath(v)
		return nil
	case certification.FieldCertPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCertPath(v)
		return nil
	case certification.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case certification.FieldIssuer:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIssuer(v)
		return nil
	}
	return fmt.Errorf("unknown Certification field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CertificationMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CertificationMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CertificationMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Certification numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CertificationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CertificationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CertificationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Certification nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CertificationMutation) ResetField(name string) error {
	switch name {
	case certification.FieldIDCardNumber:
		m.ResetIDCardNumber()
		return nil
	case certification.FieldPrivatePath:
		m.ResetPrivatePath()
		return nil
	case certification.FieldCertPath:
		m.ResetCertPath()
		return nil
	case certification.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case certification.FieldIssuer:
		m.ResetIssuer()
		return nil
	}
	return fmt.Errorf("unknown Certification field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CertificationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CertificationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CertificationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CertificationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CertificationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CertificationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CertificationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Certification unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CertificationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Certification edge %s", name)
}

// DocumentMutation represents an operation that mutates the Document nodes in the graph.
type DocumentMutation struct {
	config
	op             Op
	typ            string
	id             *string
	hash           *string
	status         *document.Status
	template_id    *string
	id_card_number *string
	expires_at     *time.Time
	signed_url     *string
	unsigned_url   *string
	paths          **model.Paths
	create_at      *time.Time
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*Document, error)
	predicates     []predicate.Document
}

var _ ent.Mutation = (*DocumentMutation)(nil)

// documentOption allows management of the mutation configuration using functional options.
type documentOption func(*DocumentMutation)

// newDocumentMutation creates new mutation for the Document entity.
func newDocumentMutation(c config, op Op, opts ...documentOption) *DocumentMutation {
	m := &DocumentMutation{
		config:        c,
		op:            op,
		typ:           TypeDocument,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDocumentID sets the ID field of the mutation.
func withDocumentID(id string) documentOption {
	return func(m *DocumentMutation) {
		var (
			err   error
			once  sync.Once
			value *Document
		)
		m.oldValue = func(ctx context.Context) (*Document, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Document.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDocument sets the old Document of the mutation.
func withDocument(node *Document) documentOption {
	return func(m *DocumentMutation) {
		m.oldValue = func(context.Context) (*Document, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DocumentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DocumentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Document entities.
func (m *DocumentMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DocumentMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DocumentMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Document.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetHash sets the "hash" field.
func (m *DocumentMutation) SetHash(s string) {
	m.hash = &s
}

// Hash returns the value of the "hash" field in the mutation.
func (m *DocumentMutation) Hash() (r string, exists bool) {
	v := m.hash
	if v == nil {
		return
	}
	return *v, true
}

// OldHash returns the old "hash" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHash: %w", err)
	}
	return oldValue.Hash, nil
}

// ResetHash resets all changes to the "hash" field.
func (m *DocumentMutation) ResetHash() {
	m.hash = nil
}

// SetStatus sets the "status" field.
func (m *DocumentMutation) SetStatus(d document.Status) {
	m.status = &d
}

// Status returns the value of the "status" field in the mutation.
func (m *DocumentMutation) Status() (r document.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldStatus(ctx context.Context) (v document.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *DocumentMutation) ResetStatus() {
	m.status = nil
}

// SetTemplateID sets the "template_id" field.
func (m *DocumentMutation) SetTemplateID(s string) {
	m.template_id = &s
}

// TemplateID returns the value of the "template_id" field in the mutation.
func (m *DocumentMutation) TemplateID() (r string, exists bool) {
	v := m.template_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTemplateID returns the old "template_id" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldTemplateID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTemplateID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTemplateID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTemplateID: %w", err)
	}
	return oldValue.TemplateID, nil
}

// ResetTemplateID resets all changes to the "template_id" field.
func (m *DocumentMutation) ResetTemplateID() {
	m.template_id = nil
}

// SetIDCardNumber sets the "id_card_number" field.
func (m *DocumentMutation) SetIDCardNumber(s string) {
	m.id_card_number = &s
}

// IDCardNumber returns the value of the "id_card_number" field in the mutation.
func (m *DocumentMutation) IDCardNumber() (r string, exists bool) {
	v := m.id_card_number
	if v == nil {
		return
	}
	return *v, true
}

// OldIDCardNumber returns the old "id_card_number" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldIDCardNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIDCardNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIDCardNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIDCardNumber: %w", err)
	}
	return oldValue.IDCardNumber, nil
}

// ResetIDCardNumber resets all changes to the "id_card_number" field.
func (m *DocumentMutation) ResetIDCardNumber() {
	m.id_card_number = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *DocumentMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *DocumentMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldExpiresAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *DocumentMutation) ResetExpiresAt() {
	m.expires_at = nil
}

// SetSignedURL sets the "signed_url" field.
func (m *DocumentMutation) SetSignedURL(s string) {
	m.signed_url = &s
}

// SignedURL returns the value of the "signed_url" field in the mutation.
func (m *DocumentMutation) SignedURL() (r string, exists bool) {
	v := m.signed_url
	if v == nil {
		return
	}
	return *v, true
}

// OldSignedURL returns the old "signed_url" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldSignedURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSignedURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSignedURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSignedURL: %w", err)
	}
	return oldValue.SignedURL, nil
}

// ClearSignedURL clears the value of the "signed_url" field.
func (m *DocumentMutation) ClearSignedURL() {
	m.signed_url = nil
	m.clearedFields[document.FieldSignedURL] = struct{}{}
}

// SignedURLCleared returns if the "signed_url" field was cleared in this mutation.
func (m *DocumentMutation) SignedURLCleared() bool {
	_, ok := m.clearedFields[document.FieldSignedURL]
	return ok
}

// ResetSignedURL resets all changes to the "signed_url" field.
func (m *DocumentMutation) ResetSignedURL() {
	m.signed_url = nil
	delete(m.clearedFields, document.FieldSignedURL)
}

// SetUnsignedURL sets the "unsigned_url" field.
func (m *DocumentMutation) SetUnsignedURL(s string) {
	m.unsigned_url = &s
}

// UnsignedURL returns the value of the "unsigned_url" field in the mutation.
func (m *DocumentMutation) UnsignedURL() (r string, exists bool) {
	v := m.unsigned_url
	if v == nil {
		return
	}
	return *v, true
}

// OldUnsignedURL returns the old "unsigned_url" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldUnsignedURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUnsignedURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUnsignedURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUnsignedURL: %w", err)
	}
	return oldValue.UnsignedURL, nil
}

// ClearUnsignedURL clears the value of the "unsigned_url" field.
func (m *DocumentMutation) ClearUnsignedURL() {
	m.unsigned_url = nil
	m.clearedFields[document.FieldUnsignedURL] = struct{}{}
}

// UnsignedURLCleared returns if the "unsigned_url" field was cleared in this mutation.
func (m *DocumentMutation) UnsignedURLCleared() bool {
	_, ok := m.clearedFields[document.FieldUnsignedURL]
	return ok
}

// ResetUnsignedURL resets all changes to the "unsigned_url" field.
func (m *DocumentMutation) ResetUnsignedURL() {
	m.unsigned_url = nil
	delete(m.clearedFields, document.FieldUnsignedURL)
}

// SetPaths sets the "paths" field.
func (m *DocumentMutation) SetPaths(value *model.Paths) {
	m.paths = &value
}

// Paths returns the value of the "paths" field in the mutation.
func (m *DocumentMutation) Paths() (r *model.Paths, exists bool) {
	v := m.paths
	if v == nil {
		return
	}
	return *v, true
}

// OldPaths returns the old "paths" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldPaths(ctx context.Context) (v *model.Paths, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPaths is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPaths requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPaths: %w", err)
	}
	return oldValue.Paths, nil
}

// ResetPaths resets all changes to the "paths" field.
func (m *DocumentMutation) ResetPaths() {
	m.paths = nil
}

// SetCreateAt sets the "create_at" field.
func (m *DocumentMutation) SetCreateAt(t time.Time) {
	m.create_at = &t
}

// CreateAt returns the value of the "create_at" field in the mutation.
func (m *DocumentMutation) CreateAt() (r time.Time, exists bool) {
	v := m.create_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateAt returns the old "create_at" field's value of the Document entity.
// If the Document object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DocumentMutation) OldCreateAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateAt: %w", err)
	}
	return oldValue.CreateAt, nil
}

// ResetCreateAt resets all changes to the "create_at" field.
func (m *DocumentMutation) ResetCreateAt() {
	m.create_at = nil
}

// Where appends a list predicates to the DocumentMutation builder.
func (m *DocumentMutation) Where(ps ...predicate.Document) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DocumentMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DocumentMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Document, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DocumentMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DocumentMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Document).
func (m *DocumentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DocumentMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.hash != nil {
		fields = append(fields, document.FieldHash)
	}
	if m.status != nil {
		fields = append(fields, document.FieldStatus)
	}
	if m.template_id != nil {
		fields = append(fields, document.FieldTemplateID)
	}
	if m.id_card_number != nil {
		fields = append(fields, document.FieldIDCardNumber)
	}
	if m.expires_at != nil {
		fields = append(fields, document.FieldExpiresAt)
	}
	if m.signed_url != nil {
		fields = append(fields, document.FieldSignedURL)
	}
	if m.unsigned_url != nil {
		fields = append(fields, document.FieldUnsignedURL)
	}
	if m.paths != nil {
		fields = append(fields, document.FieldPaths)
	}
	if m.create_at != nil {
		fields = append(fields, document.FieldCreateAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DocumentMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case document.FieldHash:
		return m.Hash()
	case document.FieldStatus:
		return m.Status()
	case document.FieldTemplateID:
		return m.TemplateID()
	case document.FieldIDCardNumber:
		return m.IDCardNumber()
	case document.FieldExpiresAt:
		return m.ExpiresAt()
	case document.FieldSignedURL:
		return m.SignedURL()
	case document.FieldUnsignedURL:
		return m.UnsignedURL()
	case document.FieldPaths:
		return m.Paths()
	case document.FieldCreateAt:
		return m.CreateAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DocumentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case document.FieldHash:
		return m.OldHash(ctx)
	case document.FieldStatus:
		return m.OldStatus(ctx)
	case document.FieldTemplateID:
		return m.OldTemplateID(ctx)
	case document.FieldIDCardNumber:
		return m.OldIDCardNumber(ctx)
	case document.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case document.FieldSignedURL:
		return m.OldSignedURL(ctx)
	case document.FieldUnsignedURL:
		return m.OldUnsignedURL(ctx)
	case document.FieldPaths:
		return m.OldPaths(ctx)
	case document.FieldCreateAt:
		return m.OldCreateAt(ctx)
	}
	return nil, fmt.Errorf("unknown Document field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DocumentMutation) SetField(name string, value ent.Value) error {
	switch name {
	case document.FieldHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHash(v)
		return nil
	case document.FieldStatus:
		v, ok := value.(document.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case document.FieldTemplateID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTemplateID(v)
		return nil
	case document.FieldIDCardNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIDCardNumber(v)
		return nil
	case document.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case document.FieldSignedURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSignedURL(v)
		return nil
	case document.FieldUnsignedURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUnsignedURL(v)
		return nil
	case document.FieldPaths:
		v, ok := value.(*model.Paths)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPaths(v)
		return nil
	case document.FieldCreateAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateAt(v)
		return nil
	}
	return fmt.Errorf("unknown Document field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DocumentMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DocumentMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DocumentMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Document numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DocumentMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(document.FieldSignedURL) {
		fields = append(fields, document.FieldSignedURL)
	}
	if m.FieldCleared(document.FieldUnsignedURL) {
		fields = append(fields, document.FieldUnsignedURL)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DocumentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DocumentMutation) ClearField(name string) error {
	switch name {
	case document.FieldSignedURL:
		m.ClearSignedURL()
		return nil
	case document.FieldUnsignedURL:
		m.ClearUnsignedURL()
		return nil
	}
	return fmt.Errorf("unknown Document nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DocumentMutation) ResetField(name string) error {
	switch name {
	case document.FieldHash:
		m.ResetHash()
		return nil
	case document.FieldStatus:
		m.ResetStatus()
		return nil
	case document.FieldTemplateID:
		m.ResetTemplateID()
		return nil
	case document.FieldIDCardNumber:
		m.ResetIDCardNumber()
		return nil
	case document.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case document.FieldSignedURL:
		m.ResetSignedURL()
		return nil
	case document.FieldUnsignedURL:
		m.ResetUnsignedURL()
		return nil
	case document.FieldPaths:
		m.ResetPaths()
		return nil
	case document.FieldCreateAt:
		m.ResetCreateAt()
		return nil
	}
	return fmt.Errorf("unknown Document field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DocumentMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DocumentMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DocumentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DocumentMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DocumentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DocumentMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DocumentMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Document unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DocumentMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Document edge %s", name)
}

// EnterpriseMutation represents an operation that mutates the Enterprise nodes in the graph.
type EnterpriseMutation struct {
	config
	op                Op
	typ               string
	id                *int
	credit_code       *string
	name              *string
	province          *string
	city              *string
	person_name       *string
	phone             *string
	idcard            *string
	is_default        *bool
	root_cert_path    *string
	root_private_path *string
	root_expires_at   *time.Time
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*Enterprise, error)
	predicates        []predicate.Enterprise
}

var _ ent.Mutation = (*EnterpriseMutation)(nil)

// enterpriseOption allows management of the mutation configuration using functional options.
type enterpriseOption func(*EnterpriseMutation)

// newEnterpriseMutation creates new mutation for the Enterprise entity.
func newEnterpriseMutation(c config, op Op, opts ...enterpriseOption) *EnterpriseMutation {
	m := &EnterpriseMutation{
		config:        c,
		op:            op,
		typ:           TypeEnterprise,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEnterpriseID sets the ID field of the mutation.
func withEnterpriseID(id int) enterpriseOption {
	return func(m *EnterpriseMutation) {
		var (
			err   error
			once  sync.Once
			value *Enterprise
		)
		m.oldValue = func(ctx context.Context) (*Enterprise, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Enterprise.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEnterprise sets the old Enterprise of the mutation.
func withEnterprise(node *Enterprise) enterpriseOption {
	return func(m *EnterpriseMutation) {
		m.oldValue = func(context.Context) (*Enterprise, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EnterpriseMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EnterpriseMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EnterpriseMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EnterpriseMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Enterprise.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreditCode sets the "credit_code" field.
func (m *EnterpriseMutation) SetCreditCode(s string) {
	m.credit_code = &s
}

// CreditCode returns the value of the "credit_code" field in the mutation.
func (m *EnterpriseMutation) CreditCode() (r string, exists bool) {
	v := m.credit_code
	if v == nil {
		return
	}
	return *v, true
}

// OldCreditCode returns the old "credit_code" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldCreditCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreditCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreditCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreditCode: %w", err)
	}
	return oldValue.CreditCode, nil
}

// ResetCreditCode resets all changes to the "credit_code" field.
func (m *EnterpriseMutation) ResetCreditCode() {
	m.credit_code = nil
}

// SetName sets the "name" field.
func (m *EnterpriseMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *EnterpriseMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *EnterpriseMutation) ResetName() {
	m.name = nil
}

// SetProvince sets the "province" field.
func (m *EnterpriseMutation) SetProvince(s string) {
	m.province = &s
}

// Province returns the value of the "province" field in the mutation.
func (m *EnterpriseMutation) Province() (r string, exists bool) {
	v := m.province
	if v == nil {
		return
	}
	return *v, true
}

// OldProvince returns the old "province" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldProvince(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProvince is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProvince requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProvince: %w", err)
	}
	return oldValue.Province, nil
}

// ResetProvince resets all changes to the "province" field.
func (m *EnterpriseMutation) ResetProvince() {
	m.province = nil
}

// SetCity sets the "city" field.
func (m *EnterpriseMutation) SetCity(s string) {
	m.city = &s
}

// City returns the value of the "city" field in the mutation.
func (m *EnterpriseMutation) City() (r string, exists bool) {
	v := m.city
	if v == nil {
		return
	}
	return *v, true
}

// OldCity returns the old "city" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldCity(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCity: %w", err)
	}
	return oldValue.City, nil
}

// ResetCity resets all changes to the "city" field.
func (m *EnterpriseMutation) ResetCity() {
	m.city = nil
}

// SetPersonName sets the "person_name" field.
func (m *EnterpriseMutation) SetPersonName(s string) {
	m.person_name = &s
}

// PersonName returns the value of the "person_name" field in the mutation.
func (m *EnterpriseMutation) PersonName() (r string, exists bool) {
	v := m.person_name
	if v == nil {
		return
	}
	return *v, true
}

// OldPersonName returns the old "person_name" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldPersonName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPersonName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPersonName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPersonName: %w", err)
	}
	return oldValue.PersonName, nil
}

// ClearPersonName clears the value of the "person_name" field.
func (m *EnterpriseMutation) ClearPersonName() {
	m.person_name = nil
	m.clearedFields[enterprise.FieldPersonName] = struct{}{}
}

// PersonNameCleared returns if the "person_name" field was cleared in this mutation.
func (m *EnterpriseMutation) PersonNameCleared() bool {
	_, ok := m.clearedFields[enterprise.FieldPersonName]
	return ok
}

// ResetPersonName resets all changes to the "person_name" field.
func (m *EnterpriseMutation) ResetPersonName() {
	m.person_name = nil
	delete(m.clearedFields, enterprise.FieldPersonName)
}

// SetPhone sets the "phone" field.
func (m *EnterpriseMutation) SetPhone(s string) {
	m.phone = &s
}

// Phone returns the value of the "phone" field in the mutation.
func (m *EnterpriseMutation) Phone() (r string, exists bool) {
	v := m.phone
	if v == nil {
		return
	}
	return *v, true
}

// OldPhone returns the old "phone" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldPhone(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPhone is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPhone requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPhone: %w", err)
	}
	return oldValue.Phone, nil
}

// ClearPhone clears the value of the "phone" field.
func (m *EnterpriseMutation) ClearPhone() {
	m.phone = nil
	m.clearedFields[enterprise.FieldPhone] = struct{}{}
}

// PhoneCleared returns if the "phone" field was cleared in this mutation.
func (m *EnterpriseMutation) PhoneCleared() bool {
	_, ok := m.clearedFields[enterprise.FieldPhone]
	return ok
}

// ResetPhone resets all changes to the "phone" field.
func (m *EnterpriseMutation) ResetPhone() {
	m.phone = nil
	delete(m.clearedFields, enterprise.FieldPhone)
}

// SetIdcard sets the "idcard" field.
func (m *EnterpriseMutation) SetIdcard(s string) {
	m.idcard = &s
}

// Idcard returns the value of the "idcard" field in the mutation.
func (m *EnterpriseMutation) Idcard() (r string, exists bool) {
	v := m.idcard
	if v == nil {
		return
	}
	return *v, true
}

// OldIdcard returns the old "idcard" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldIdcard(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIdcard is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIdcard requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIdcard: %w", err)
	}
	return oldValue.Idcard, nil
}

// ClearIdcard clears the value of the "idcard" field.
func (m *EnterpriseMutation) ClearIdcard() {
	m.idcard = nil
	m.clearedFields[enterprise.FieldIdcard] = struct{}{}
}

// IdcardCleared returns if the "idcard" field was cleared in this mutation.
func (m *EnterpriseMutation) IdcardCleared() bool {
	_, ok := m.clearedFields[enterprise.FieldIdcard]
	return ok
}

// ResetIdcard resets all changes to the "idcard" field.
func (m *EnterpriseMutation) ResetIdcard() {
	m.idcard = nil
	delete(m.clearedFields, enterprise.FieldIdcard)
}

// SetIsDefault sets the "is_default" field.
func (m *EnterpriseMutation) SetIsDefault(b bool) {
	m.is_default = &b
}

// IsDefault returns the value of the "is_default" field in the mutation.
func (m *EnterpriseMutation) IsDefault() (r bool, exists bool) {
	v := m.is_default
	if v == nil {
		return
	}
	return *v, true
}

// OldIsDefault returns the old "is_default" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldIsDefault(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsDefault is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsDefault requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsDefault: %w", err)
	}
	return oldValue.IsDefault, nil
}

// ResetIsDefault resets all changes to the "is_default" field.
func (m *EnterpriseMutation) ResetIsDefault() {
	m.is_default = nil
}

// SetRootCertPath sets the "root_cert_path" field.
func (m *EnterpriseMutation) SetRootCertPath(s string) {
	m.root_cert_path = &s
}

// RootCertPath returns the value of the "root_cert_path" field in the mutation.
func (m *EnterpriseMutation) RootCertPath() (r string, exists bool) {
	v := m.root_cert_path
	if v == nil {
		return
	}
	return *v, true
}

// OldRootCertPath returns the old "root_cert_path" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldRootCertPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRootCertPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRootCertPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRootCertPath: %w", err)
	}
	return oldValue.RootCertPath, nil
}

// ClearRootCertPath clears the value of the "root_cert_path" field.
func (m *EnterpriseMutation) ClearRootCertPath() {
	m.root_cert_path = nil
	m.clearedFields[enterprise.FieldRootCertPath] = struct{}{}
}

// RootCertPathCleared returns if the "root_cert_path" field was cleared in this mutation.
func (m *EnterpriseMutation) RootCertPathCleared() bool {
	_, ok := m.clearedFields[enterprise.FieldRootCertPath]
	return ok
}

// ResetRootCertPath resets all changes to the "root_cert_path" field.
func (m *EnterpriseMutation) ResetRootCertPath() {
	m.root_cert_path = nil
	delete(m.clearedFields, enterprise.FieldRootCertPath)
}

// SetRootPrivatePath sets the "root_private_path" field.
func (m *EnterpriseMutation) SetRootPrivatePath(s string) {
	m.root_private_path = &s
}

// RootPrivatePath returns the value of the "root_private_path" field in the mutation.
func (m *EnterpriseMutation) RootPrivatePath() (r string, exists bool) {
	v := m.root_private_path
	if v == nil {
		return
	}
	return *v, true
}

// OldRootPrivatePath returns the old "root_private_path" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldRootPrivatePath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRootPrivatePath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRootPrivatePath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRootPrivatePath: %w", err)
	}
	return oldValue.RootPrivatePath, nil
}

// ClearRootPrivatePath clears the value of the "root_private_path" field.
func (m *EnterpriseMutation) ClearRootPrivatePath() {
	m.root_private_path = nil
	m.clearedFields[enterprise.FieldRootPrivatePath] = struct{}{}
}

// RootPrivatePathCleared returns if the "root_private_path" field was cleared in this mutation.
func (m *EnterpriseMutation) RootPrivatePathCleared() bool {
	_, ok := m.clearedFields[enterprise.FieldRootPrivatePath]
	return ok
}

// ResetRootPrivatePath resets all changes to the "root_private_path" field.
func (m *EnterpriseMutation) ResetRootPrivatePath() {
	m.root_private_path = nil
	delete(m.clearedFields, enterprise.FieldRootPrivatePath)
}

// SetRootExpiresAt sets the "root_expires_at" field.
func (m *EnterpriseMutation) SetRootExpiresAt(t time.Time) {
	m.root_expires_at = &t
}

// RootExpiresAt returns the value of the "root_expires_at" field in the mutation.
func (m *EnterpriseMutation) RootExpiresAt() (r time.Time, exists bool) {
	v := m.root_expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldRootExpiresAt returns the old "root_expires_at" field's value of the Enterprise entity.
// If the Enterprise object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseMutation) OldRootExpiresAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRootExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRootExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRootExpiresAt: %w", err)
	}
	return oldValue.RootExpiresAt, nil
}

// ClearRootExpiresAt clears the value of the "root_expires_at" field.
func (m *EnterpriseMutation) ClearRootExpiresAt() {
	m.root_expires_at = nil
	m.clearedFields[enterprise.FieldRootExpiresAt] = struct{}{}
}

// RootExpiresAtCleared returns if the "root_expires_at" field was cleared in this mutation.
func (m *EnterpriseMutation) RootExpiresAtCleared() bool {
	_, ok := m.clearedFields[enterprise.FieldRootExpiresAt]
	return ok
}

// ResetRootExpiresAt resets all changes to the "root_expires_at" field.
func (m *EnterpriseMutation) ResetRootExpiresAt() {
	m.root_expires_at = nil
	delete(m.clearedFields, enterprise.FieldRootExpiresAt)
}

// Where appends a list predicates to the EnterpriseMutation builder.
func (m *EnterpriseMutation) Where(ps ...predicate.Enterprise) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EnterpriseMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EnterpriseMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Enterprise, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EnterpriseMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EnterpriseMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Enterprise).
func (m *EnterpriseMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EnterpriseMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.credit_code != nil {
		fields = append(fields, enterprise.FieldCreditCode)
	}
	if m.name != nil {
		fields = append(fields, enterprise.FieldName)
	}
	if m.province != nil {
		fields = append(fields, enterprise.FieldProvince)
	}
	if m.city != nil {
		fields = append(fields, enterprise.FieldCity)
	}
	if m.person_name != nil {
		fields = append(fields, enterprise.FieldPersonName)
	}
	if m.phone != nil {
		fields = append(fields, enterprise.FieldPhone)
	}
	if m.idcard != nil {
		fields = append(fields, enterprise.FieldIdcard)
	}
	if m.is_default != nil {
		fields = append(fields, enterprise.FieldIsDefault)
	}
	if m.root_cert_path != nil {
		fields = append(fields, enterprise.FieldRootCertPath)
	}
	if m.root_private_path != nil {
		fields = append(fields, enterprise.FieldRootPrivatePath)
	}
	if m.root_expires_at != nil {
		fields = append(fields, enterprise.FieldRootExpiresAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EnterpriseMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case enterprise.FieldCreditCode:
		return m.CreditCode()
	case enterprise.FieldName:
		return m.Name()
	case enterprise.FieldProvince:
		return m.Province()
	case enterprise.FieldCity:
		return m.City()
	case enterprise.FieldPersonName:
		return m.PersonName()
	case enterprise.FieldPhone:
		return m.Phone()
	case enterprise.FieldIdcard:
		return m.Idcard()
	case enterprise.FieldIsDefault:
		return m.IsDefault()
	case enterprise.FieldRootCertPath:
		return m.RootCertPath()
	case enterprise.FieldRootPrivatePath:
		return m.RootPrivatePath()
	case enterprise.FieldRootExpiresAt:
		return m.RootExpiresAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EnterpriseMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case enterprise.FieldCreditCode:
		return m.OldCreditCode(ctx)
	case enterprise.FieldName:
		return m.OldName(ctx)
	case enterprise.FieldProvince:
		return m.OldProvince(ctx)
	case enterprise.FieldCity:
		return m.OldCity(ctx)
	case enterprise.FieldPersonName:
		return m.OldPersonName(ctx)
	case enterprise.FieldPhone:
		return m.OldPhone(ctx)
	case enterprise.FieldIdcard:
		return m.OldIdcard(ctx)
	case enterprise.FieldIsDefault:
		return m.OldIsDefault(ctx)
	case enterprise.FieldRootCertPath:
		return m.OldRootCertPath(ctx)
	case enterprise.FieldRootPrivatePath:
		return m.OldRootPrivatePath(ctx)
	case enterprise.FieldRootExpiresAt:
		return m.OldRootExpiresAt(ctx)
	}
	return nil, fmt.Errorf("unknown Enterprise field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EnterpriseMutation) SetField(name string, value ent.Value) error {
	switch name {
	case enterprise.FieldCreditCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreditCode(v)
		return nil
	case enterprise.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case enterprise.FieldProvince:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProvince(v)
		return nil
	case enterprise.FieldCity:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCity(v)
		return nil
	case enterprise.FieldPersonName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPersonName(v)
		return nil
	case enterprise.FieldPhone:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPhone(v)
		return nil
	case enterprise.FieldIdcard:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIdcard(v)
		return nil
	case enterprise.FieldIsDefault:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsDefault(v)
		return nil
	case enterprise.FieldRootCertPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRootCertPath(v)
		return nil
	case enterprise.FieldRootPrivatePath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRootPrivatePath(v)
		return nil
	case enterprise.FieldRootExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRootExpiresAt(v)
		return nil
	}
	return fmt.Errorf("unknown Enterprise field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EnterpriseMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EnterpriseMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EnterpriseMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Enterprise numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EnterpriseMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(enterprise.FieldPersonName) {
		fields = append(fields, enterprise.FieldPersonName)
	}
	if m.FieldCleared(enterprise.FieldPhone) {
		fields = append(fields, enterprise.FieldPhone)
	}
	if m.FieldCleared(enterprise.FieldIdcard) {
		fields = append(fields, enterprise.FieldIdcard)
	}
	if m.FieldCleared(enterprise.FieldRootCertPath) {
		fields = append(fields, enterprise.FieldRootCertPath)
	}
	if m.FieldCleared(enterprise.FieldRootPrivatePath) {
		fields = append(fields, enterprise.FieldRootPrivatePath)
	}
	if m.FieldCleared(enterprise.FieldRootExpiresAt) {
		fields = append(fields, enterprise.FieldRootExpiresAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EnterpriseMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EnterpriseMutation) ClearField(name string) error {
	switch name {
	case enterprise.FieldPersonName:
		m.ClearPersonName()
		return nil
	case enterprise.FieldPhone:
		m.ClearPhone()
		return nil
	case enterprise.FieldIdcard:
		m.ClearIdcard()
		return nil
	case enterprise.FieldRootCertPath:
		m.ClearRootCertPath()
		return nil
	case enterprise.FieldRootPrivatePath:
		m.ClearRootPrivatePath()
		return nil
	case enterprise.FieldRootExpiresAt:
		m.ClearRootExpiresAt()
		return nil
	}
	return fmt.Errorf("unknown Enterprise nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EnterpriseMutation) ResetField(name string) error {
	switch name {
	case enterprise.FieldCreditCode:
		m.ResetCreditCode()
		return nil
	case enterprise.FieldName:
		m.ResetName()
		return nil
	case enterprise.FieldProvince:
		m.ResetProvince()
		return nil
	case enterprise.FieldCity:
		m.ResetCity()
		return nil
	case enterprise.FieldPersonName:
		m.ResetPersonName()
		return nil
	case enterprise.FieldPhone:
		m.ResetPhone()
		return nil
	case enterprise.FieldIdcard:
		m.ResetIdcard()
		return nil
	case enterprise.FieldIsDefault:
		m.ResetIsDefault()
		return nil
	case enterprise.FieldRootCertPath:
		m.ResetRootCertPath()
		return nil
	case enterprise.FieldRootPrivatePath:
		m.ResetRootPrivatePath()
		return nil
	case enterprise.FieldRootExpiresAt:
		m.ResetRootExpiresAt()
		return nil
	}
	return fmt.Errorf("unknown Enterprise field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EnterpriseMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EnterpriseMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EnterpriseMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EnterpriseMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EnterpriseMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EnterpriseMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EnterpriseMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Enterprise unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EnterpriseMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Enterprise edge %s", name)
}

// EnterpriseCertificationMutation represents an operation that mutates the EnterpriseCertification nodes in the graph.
type EnterpriseCertificationMutation struct {
	config
	op            Op
	typ           string
	id            *int
	credit_code   *string
	issuer        *string
	private_path  *string
	cert_path     *string
	expires_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*EnterpriseCertification, error)
	predicates    []predicate.EnterpriseCertification
}

var _ ent.Mutation = (*EnterpriseCertificationMutation)(nil)

// enterprisecertificationOption allows management of the mutation configuration using functional options.
type enterprisecertificationOption func(*EnterpriseCertificationMutation)

// newEnterpriseCertificationMutation creates new mutation for the EnterpriseCertification entity.
func newEnterpriseCertificationMutation(c config, op Op, opts ...enterprisecertificationOption) *EnterpriseCertificationMutation {
	m := &EnterpriseCertificationMutation{
		config:        c,
		op:            op,
		typ:           TypeEnterpriseCertification,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEnterpriseCertificationID sets the ID field of the mutation.
func withEnterpriseCertificationID(id int) enterprisecertificationOption {
	return func(m *EnterpriseCertificationMutation) {
		var (
			err   error
			once  sync.Once
			value *EnterpriseCertification
		)
		m.oldValue = func(ctx context.Context) (*EnterpriseCertification, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().EnterpriseCertification.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEnterpriseCertification sets the old EnterpriseCertification of the mutation.
func withEnterpriseCertification(node *EnterpriseCertification) enterprisecertificationOption {
	return func(m *EnterpriseCertificationMutation) {
		m.oldValue = func(context.Context) (*EnterpriseCertification, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EnterpriseCertificationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EnterpriseCertificationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EnterpriseCertificationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EnterpriseCertificationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().EnterpriseCertification.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreditCode sets the "credit_code" field.
func (m *EnterpriseCertificationMutation) SetCreditCode(s string) {
	m.credit_code = &s
}

// CreditCode returns the value of the "credit_code" field in the mutation.
func (m *EnterpriseCertificationMutation) CreditCode() (r string, exists bool) {
	v := m.credit_code
	if v == nil {
		return
	}
	return *v, true
}

// OldCreditCode returns the old "credit_code" field's value of the EnterpriseCertification entity.
// If the EnterpriseCertification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseCertificationMutation) OldCreditCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreditCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreditCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreditCode: %w", err)
	}
	return oldValue.CreditCode, nil
}

// ResetCreditCode resets all changes to the "credit_code" field.
func (m *EnterpriseCertificationMutation) ResetCreditCode() {
	m.credit_code = nil
}

// SetIssuer sets the "issuer" field.
func (m *EnterpriseCertificationMutation) SetIssuer(s string) {
	m.issuer = &s
}

// Issuer returns the value of the "issuer" field in the mutation.
func (m *EnterpriseCertificationMutation) Issuer() (r string, exists bool) {
	v := m.issuer
	if v == nil {
		return
	}
	return *v, true
}

// OldIssuer returns the old "issuer" field's value of the EnterpriseCertification entity.
// If the EnterpriseCertification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseCertificationMutation) OldIssuer(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIssuer is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIssuer requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIssuer: %w", err)
	}
	return oldValue.Issuer, nil
}

// ResetIssuer resets all changes to the "issuer" field.
func (m *EnterpriseCertificationMutation) ResetIssuer() {
	m.issuer = nil
}

// SetPrivatePath sets the "private_path" field.
func (m *EnterpriseCertificationMutation) SetPrivatePath(s string) {
	m.private_path = &s
}

// PrivatePath returns the value of the "private_path" field in the mutation.
func (m *EnterpriseCertificationMutation) PrivatePath() (r string, exists bool) {
	v := m.private_path
	if v == nil {
		return
	}
	return *v, true
}

// OldPrivatePath returns the old "private_path" field's value of the EnterpriseCertification entity.
// If the EnterpriseCertification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseCertificationMutation) OldPrivatePath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrivatePath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrivatePath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrivatePath: %w", err)
	}
	return oldValue.PrivatePath, nil
}

// ResetPrivatePath resets all changes to the "private_path" field.
func (m *EnterpriseCertificationMutation) ResetPrivatePath() {
	m.private_path = nil
}

// SetCertPath sets the "cert_path" field.
func (m *EnterpriseCertificationMutation) SetCertPath(s string) {
	m.cert_path = &s
}

// CertPath returns the value of the "cert_path" field in the mutation.
func (m *EnterpriseCertificationMutation) CertPath() (r string, exists bool) {
	v := m.cert_path
	if v == nil {
		return
	}
	return *v, true
}

// OldCertPath returns the old "cert_path" field's value of the EnterpriseCertification entity.
// If the EnterpriseCertification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseCertificationMutation) OldCertPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCertPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCertPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCertPath: %w", err)
	}
	return oldValue.CertPath, nil
}

// ResetCertPath resets all changes to the "cert_path" field.
func (m *EnterpriseCertificationMutation) ResetCertPath() {
	m.cert_path = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *EnterpriseCertificationMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *EnterpriseCertificationMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the EnterpriseCertification entity.
// If the EnterpriseCertification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnterpriseCertificationMutation) OldExpiresAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *EnterpriseCertificationMutation) ResetExpiresAt() {
	m.expires_at = nil
}

// Where appends a list predicates to the EnterpriseCertificationMutation builder.
func (m *EnterpriseCertificationMutation) Where(ps ...predicate.EnterpriseCertification) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EnterpriseCertificationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EnterpriseCertificationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.EnterpriseCertification, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EnterpriseCertificationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EnterpriseCertificationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (EnterpriseCertification).
func (m *EnterpriseCertificationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EnterpriseCertificationMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.credit_code != nil {
		fields = append(fields, enterprisecertification.FieldCreditCode)
	}
	if m.issuer != nil {
		fields = append(fields, enterprisecertification.FieldIssuer)
	}
	if m.private_path != nil {
		fields = append(fields, enterprisecertification.FieldPrivatePath)
	}
	if m.cert_path != nil {
		fields = append(fields, enterprisecertification.FieldCertPath)
	}
	if m.expires_at != nil {
		fields = append(fields, enterprisecertification.FieldExpiresAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EnterpriseCertificationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case enterprisecertification.FieldCreditCode:
		return m.CreditCode()
	case enterprisecertification.FieldIssuer:
		return m.Issuer()
	case enterprisecertification.FieldPrivatePath:
		return m.PrivatePath()
	case enterprisecertification.FieldCertPath:
		return m.CertPath()
	case enterprisecertification.FieldExpiresAt:
		return m.ExpiresAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EnterpriseCertificationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case enterprisecertification.FieldCreditCode:
		return m.OldCreditCode(ctx)
	case enterprisecertification.FieldIssuer:
		return m.OldIssuer(ctx)
	case enterprisecertification.FieldPrivatePath:
		return m.OldPrivatePath(ctx)
	case enterprisecertification.FieldCertPath:
		return m.OldCertPath(ctx)
	case enterprisecertification.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	}
	return nil, fmt.Errorf("unknown EnterpriseCertification field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EnterpriseCertificationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case enterprisecertification.FieldCreditCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreditCode(v)
		return nil
	case enterprisecertification.FieldIssuer:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIssuer(v)
		return nil
	case enterprisecertification.FieldPrivatePath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrivatePath(v)
		return nil
	case enterprisecertification.FieldCertPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCertPath(v)
		return nil
	case enterprisecertification.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	}
	return fmt.Errorf("unknown EnterpriseCertification field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EnterpriseCertificationMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EnterpriseCertificationMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EnterpriseCertificationMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown EnterpriseCertification numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EnterpriseCertificationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EnterpriseCertificationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EnterpriseCertificationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown EnterpriseCertification nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EnterpriseCertificationMutation) ResetField(name string) error {
	switch name {
	case enterprisecertification.FieldCreditCode:
		m.ResetCreditCode()
		return nil
	case enterprisecertification.FieldIssuer:
		m.ResetIssuer()
		return nil
	case enterprisecertification.FieldPrivatePath:
		m.ResetPrivatePath()
		return nil
	case enterprisecertification.FieldCertPath:
		m.ResetCertPath()
		return nil
	case enterprisecertification.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	}
	return fmt.Errorf("unknown EnterpriseCertification field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EnterpriseCertificationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EnterpriseCertificationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EnterpriseCertificationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EnterpriseCertificationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EnterpriseCertificationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EnterpriseCertificationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EnterpriseCertificationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown EnterpriseCertification unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EnterpriseCertificationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown EnterpriseCertification edge %s", name)
}
