// Code generated by ent, DO NOT EDIT.

package ent

import (
	"auroraride.com/edocseal/internal/ent/certification"
	"auroraride.com/edocseal/internal/ent/document"
	"auroraride.com/edocseal/internal/ent/enterprise"
	"auroraride.com/edocseal/internal/ent/enterprisecertification"
	"auroraride.com/edocseal/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	certificationFields := schema.Certification{}.Fields()
	_ = certificationFields
	// certificationDescIDCardNumber is the schema descriptor for id_card_number field.
	certificationDescIDCardNumber := certificationFields[0].Descriptor()
	// certification.IDCardNumberValidator is a validator for the "id_card_number" field. It is called by the builders before save.
	certification.IDCardNumberValidator = certificationDescIDCardNumber.Validators[0].(func(string) error)
	// certificationDescPrivatePath is the schema descriptor for private_path field.
	certificationDescPrivatePath := certificationFields[1].Descriptor()
	// certification.PrivatePathValidator is a validator for the "private_path" field. It is called by the builders before save.
	certification.PrivatePathValidator = certificationDescPrivatePath.Validators[0].(func(string) error)
	// certificationDescCertPath is the schema descriptor for cert_path field.
	certificationDescCertPath := certificationFields[2].Descriptor()
	// certification.CertPathValidator is a validator for the "cert_path" field. It is called by the builders before save.
	certification.CertPathValidator = certificationDescCertPath.Validators[0].(func(string) error)
	// certificationDescIssuer is the schema descriptor for issuer field.
	certificationDescIssuer := certificationFields[4].Descriptor()
	// certification.DefaultIssuer holds the default value on creation for the issuer field.
	certification.DefaultIssuer = certificationDescIssuer.Default.(string)
	// certification.IssuerValidator is a validator for the "issuer" field. It is called by the builders before save.
	certification.IssuerValidator = certificationDescIssuer.Validators[0].(func(string) error)
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescIDCardNumber is the schema descriptor for id_card_number field.
	documentDescIDCardNumber := documentFields[4].Descriptor()
	// document.IDCardNumberValidator is a validator for the "id_card_number" field. It is called by the builders before save.
	document.IDCardNumberValidator = documentDescIDCardNumber.Validators[0].(func(string) error)
	enterpriseFields := schema.Enterprise{}.Fields()
	_ = enterpriseFields
	// enterpriseDescCreditCode is the schema descriptor for credit_code field.
	enterpriseDescCreditCode := enterpriseFields[0].Descriptor()
	// enterprise.CreditCodeValidator is a validator for the "credit_code" field. It is called by the builders before save.
	enterprise.CreditCodeValidator = enterpriseDescCreditCode.Validators[0].(func(string) error)
	// enterpriseDescName is the schema descriptor for name field.
	enterpriseDescName := enterpriseFields[1].Descriptor()
	// enterprise.NameValidator is a validator for the "name" field. It is called by the builders before save.
	enterprise.NameValidator = enterpriseDescName.Validators[0].(func(string) error)
	// enterpriseDescProvince is the schema descriptor for province field.
	enterpriseDescProvince := enterpriseFields[2].Descriptor()
	// enterprise.ProvinceValidator is a validator for the "province" field. It is called by the builders before save.
	enterprise.ProvinceValidator = enterpriseDescProvince.Validators[0].(func(string) error)
	// enterpriseDescCity is the schema descriptor for city field.
	enterpriseDescCity := enterpriseFields[3].Descriptor()
	// enterprise.CityValidator is a validator for the "city" field. It is called by the builders before save.
	enterprise.CityValidator = enterpriseDescCity.Validators[0].(func(string) error)
	// enterpriseDescPersonName is the schema descriptor for person_name field.
	enterpriseDescPersonName := enterpriseFields[4].Descriptor()
	// enterprise.PersonNameValidator is a validator for the "person_name" field. It is called by the builders before save.
	enterprise.PersonNameValidator = enterpriseDescPersonName.Validators[0].(func(string) error)
	// enterpriseDescPhone is the schema descriptor for phone field.
	enterpriseDescPhone := enterpriseFields[5].Descriptor()
	// enterprise.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	enterprise.PhoneValidator = enterpriseDescPhone.Validators[0].(func(string) error)
	// enterpriseDescIdcard is the schema descriptor for idcard field.
	enterpriseDescIdcard := enterpriseFields[6].Descriptor()
	// enterprise.IdcardValidator is a validator for the "idcard" field. It is called by the builders before save.
	enterprise.IdcardValidator = enterpriseDescIdcard.Validators[0].(func(string) error)
	// enterpriseDescIsDefault is the schema descriptor for is_default field.
	enterpriseDescIsDefault := enterpriseFields[7].Descriptor()
	// enterprise.DefaultIsDefault holds the default value on creation for the is_default field.
	enterprise.DefaultIsDefault = enterpriseDescIsDefault.Default.(bool)
	// enterpriseDescRootCertPath is the schema descriptor for root_cert_path field.
	enterpriseDescRootCertPath := enterpriseFields[8].Descriptor()
	// enterprise.RootCertPathValidator is a validator for the "root_cert_path" field. It is called by the builders before save.
	enterprise.RootCertPathValidator = enterpriseDescRootCertPath.Validators[0].(func(string) error)
	// enterpriseDescRootPrivatePath is the schema descriptor for root_private_path field.
	enterpriseDescRootPrivatePath := enterpriseFields[9].Descriptor()
	// enterprise.RootPrivatePathValidator is a validator for the "root_private_path" field. It is called by the builders before save.
	enterprise.RootPrivatePathValidator = enterpriseDescRootPrivatePath.Validators[0].(func(string) error)
	enterprisecertificationFields := schema.EnterpriseCertification{}.Fields()
	_ = enterprisecertificationFields
	// enterprisecertificationDescCreditCode is the schema descriptor for credit_code field.
	enterprisecertificationDescCreditCode := enterprisecertificationFields[0].Descriptor()
	// enterprisecertification.CreditCodeValidator is a validator for the "credit_code" field. It is called by the builders before save.
	enterprisecertification.CreditCodeValidator = enterprisecertificationDescCreditCode.Validators[0].(func(string) error)
	// enterprisecertificationDescIssuer is the schema descriptor for issuer field.
	enterprisecertificationDescIssuer := enterprisecertificationFields[1].Descriptor()
	// enterprisecertification.IssuerValidator is a validator for the "issuer" field. It is called by the builders before save.
	enterprisecertification.IssuerValidator = enterprisecertificationDescIssuer.Validators[0].(func(string) error)
	// enterprisecertificationDescPrivatePath is the schema descriptor for private_path field.
	enterprisecertificationDescPrivatePath := enterprisecertificationFields[2].Descriptor()
	// enterprisecertification.PrivatePathValidator is a validator for the "private_path" field. It is called by the builders before save.
	enterprisecertification.PrivatePathValidator = enterprisecertificationDescPrivatePath.Validators[0].(func(string) error)
	// enterprisecertificationDescCertPath is the schema descriptor for cert_path field.
	enterprisecertificationDescCertPath := enterprisecertificationFields[3].Descriptor()
	// enterprisecertification.CertPathValidator is a validator for the "cert_path" field. It is called by the builders before save.
	enterprisecertification.CertPathValidator = enterprisecertificationDescCertPath.Validators[0].(func(string) error)
}
