// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: contract.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextAlign int32

const (
	TextAlign_TEXT_ALIGN_UNSPECIFIED TextAlign = 0 // 未知对齐方式
	TextAlign_TEXT_ALIGN_LEFT        TextAlign = 1 // 左对齐
	TextAlign_TEXT_ALIGN_CENTER      TextAlign = 2 // 居中对齐
	TextAlign_TEXT_ALIGN_RIGHT       TextAlign = 3 // 右对齐
)

// Enum value maps for TextAlign.
var (
	TextAlign_name = map[int32]string{
		0: "TEXT_ALIGN_UNSPECIFIED",
		1: "TEXT_ALIGN_LEFT",
		2: "TEXT_ALIGN_CENTER",
		3: "TEXT_ALIGN_RIGHT",
	}
	TextAlign_value = map[string]int32{
		"TEXT_ALIGN_UNSPECIFIED": 0,
		"TEXT_ALIGN_LEFT":        1,
		"TEXT_ALIGN_CENTER":      2,
		"TEXT_ALIGN_RIGHT":       3,
	}
)

func (x TextAlign) Enum() *TextAlign {
	p := new(TextAlign)
	*p = x
	return p
}

func (x TextAlign) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextAlign) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[0].Descriptor()
}

func (TextAlign) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[0]
}

func (x TextAlign) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextAlign.Descriptor instead.
func (TextAlign) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

type SignStatus int32

const (
	SignStatus_SIGN_STATUS_UNSPECIFIED SignStatus = 0 // 未知状态
	SignStatus_SIGN_STATUS_SUCCESS     SignStatus = 1 // 签署成功
	SignStatus_SIGN_STATUS_FAIL        SignStatus = 2 // 签署失败
)

// Enum value maps for SignStatus.
var (
	SignStatus_name = map[int32]string{
		0: "SIGN_STATUS_UNSPECIFIED",
		1: "SIGN_STATUS_SUCCESS",
		2: "SIGN_STATUS_FAIL",
	}
	SignStatus_value = map[string]int32{
		"SIGN_STATUS_UNSPECIFIED": 0,
		"SIGN_STATUS_SUCCESS":     1,
		"SIGN_STATUS_FAIL":        2,
	}
)

func (x SignStatus) Enum() *SignStatus {
	p := new(SignStatus)
	*p = x
	return p
}

func (x SignStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[1].Descriptor()
}

func (SignStatus) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[1]
}

func (x SignStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignStatus.Descriptor instead.
func (SignStatus) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

// 创建合同字段
type ContractFormField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ContractFormField_Text
	//	*ContractFormField_Checkbox
	//	*ContractFormField_Table
	//	*ContractFormField_UrlAttachment
	Value         isContractFormField_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractFormField) Reset() {
	*x = ContractFormField{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractFormField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractFormField) ProtoMessage() {}

func (x *ContractFormField) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractFormField.ProtoReflect.Descriptor instead.
func (*ContractFormField) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *ContractFormField) GetValue() isContractFormField_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ContractFormField) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*ContractFormField_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ContractFormField) GetCheckbox() bool {
	if x != nil {
		if x, ok := x.Value.(*ContractFormField_Checkbox); ok {
			return x.Checkbox
		}
	}
	return false
}

func (x *ContractFormField) GetTable() *ContractTable {
	if x != nil {
		if x, ok := x.Value.(*ContractFormField_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *ContractFormField) GetUrlAttachment() *ContractUrlAttachment {
	if x != nil {
		if x, ok := x.Value.(*ContractFormField_UrlAttachment); ok {
			return x.UrlAttachment
		}
	}
	return nil
}

type isContractFormField_Value interface {
	isContractFormField_Value()
}

type ContractFormField_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // 文本
}

type ContractFormField_Checkbox struct {
	Checkbox bool `protobuf:"varint,2,opt,name=checkbox,proto3,oneof"` // 勾选
}

type ContractFormField_Table struct {
	Table *ContractTable `protobuf:"bytes,3,opt,name=table,proto3,oneof"` // 表格
}

type ContractFormField_UrlAttachment struct {
	UrlAttachment *ContractUrlAttachment `protobuf:"bytes,4,opt,name=url_attachment,json=urlAttachment,proto3,oneof"` // 附件URL
}

func (*ContractFormField_Text) isContractFormField_Value() {}

func (*ContractFormField_Checkbox) isContractFormField_Value() {}

func (*ContractFormField_Table) isContractFormField_Value() {}

func (*ContractFormField_UrlAttachment) isContractFormField_Value() {}

type ContractTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ContractTableColumn `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"` // 表格列配置
	Rows          []*ContractTableRow    `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`       // 表格行数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractTable) Reset() {
	*x = ContractTable{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractTable) ProtoMessage() {}

func (x *ContractTable) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractTable.ProtoReflect.Descriptor instead.
func (*ContractTable) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *ContractTable) GetColumns() []*ContractTableColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ContractTable) GetRows() []*ContractTableRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ContractUrlAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`   // 附件URL
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 附件名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractUrlAttachment) Reset() {
	*x = ContractUrlAttachment{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractUrlAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractUrlAttachment) ProtoMessage() {}

func (x *ContractUrlAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractUrlAttachment.ProtoReflect.Descriptor instead.
func (*ContractUrlAttachment) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *ContractUrlAttachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ContractUrlAttachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContractTableColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                        // 表格头名称
	Scale         float64                `protobuf:"fixed64,2,opt,name=scale,proto3" json:"scale,omitempty"`                        // 列宽度百分比
	Align         *TextAlign             `protobuf:"varint,3,opt,name=align,proto3,enum=pb.TextAlign,oneof" json:"align,omitempty"` // 列对齐方式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractTableColumn) Reset() {
	*x = ContractTableColumn{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractTableColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractTableColumn) ProtoMessage() {}

func (x *ContractTableColumn) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractTableColumn.ProtoReflect.Descriptor instead.
func (*ContractTableColumn) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ContractTableColumn) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *ContractTableColumn) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ContractTableColumn) GetAlign() TextAlign {
	if x != nil && x.Align != nil {
		return *x.Align
	}
	return TextAlign_TEXT_ALIGN_UNSPECIFIED
}

type ContractTableRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []string               `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"` // 表格行数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractTableRow) Reset() {
	*x = ContractTableRow{}
	mi := &file_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractTableRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractTableRow) ProtoMessage() {}

func (x *ContractTableRow) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractTableRow.ProtoReflect.Descriptor instead.
func (*ContractTableRow) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ContractTableRow) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

// 创建合同请求
type ContractServiceCreateRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TemplateId    string                        `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`                                                 // 模板编号
	Values        map[string]*ContractFormField `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 合同模板字段，key为字段名，value为字段值
	Idcard        string                        `protobuf:"bytes,3,opt,name=idcard,proto3" json:"idcard,omitempty"`                                                                           // 用户身份证号
	Expire        int64                         `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"`                                                                          // 合同有效截止日期（北京时间，时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractServiceCreateRequest) Reset() {
	*x = ContractServiceCreateRequest{}
	mi := &file_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractServiceCreateRequest) ProtoMessage() {}

func (x *ContractServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ContractServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{5}
}

func (x *ContractServiceCreateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ContractServiceCreateRequest) GetValues() map[string]*ContractFormField {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ContractServiceCreateRequest) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

func (x *ContractServiceCreateRequest) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

// 创建合同响应
type ContractServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                  // 创建合同合同文件地址
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"` // 待签约文档编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractServiceCreateResponse) Reset() {
	*x = ContractServiceCreateResponse{}
	mi := &file_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractServiceCreateResponse) ProtoMessage() {}

func (x *ContractServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ContractServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{6}
}

func (x *ContractServiceCreateResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ContractServiceCreateResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

// 合同签署请求
type ContractServiceSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"` // 待签约文档编号
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`              // 个人签章图片（base64编码）
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                // 签署人
	Province      string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`        // 省份
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`                // 城市
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`          // 地址
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`              // 手机号
	Idcard        string                 `protobuf:"bytes,8,opt,name=idcard,proto3" json:"idcard,omitempty"`            // 身份证号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractServiceSignRequest) Reset() {
	*x = ContractServiceSignRequest{}
	mi := &file_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractServiceSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractServiceSignRequest) ProtoMessage() {}

func (x *ContractServiceSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractServiceSignRequest.ProtoReflect.Descriptor instead.
func (*ContractServiceSignRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{7}
}

func (x *ContractServiceSignRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ContractServiceSignRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContractServiceSignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractServiceSignRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ContractServiceSignRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ContractServiceSignRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContractServiceSignRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ContractServiceSignRequest) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

// 合同签署响应
type ContractServiceSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SignStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=pb.SignStatus" json:"status,omitempty"` // 签署状态 0:成功，1:失败
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                           // 已签署合同文件地址
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                   // 其他消息，例如错误消息，成功时为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractServiceSignResponse) Reset() {
	*x = ContractServiceSignResponse{}
	mi := &file_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractServiceSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractServiceSignResponse) ProtoMessage() {}

func (x *ContractServiceSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractServiceSignResponse.ProtoReflect.Descriptor instead.
func (*ContractServiceSignResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{8}
}

func (x *ContractServiceSignResponse) GetStatus() SignStatus {
	if x != nil {
		return x.Status
	}
	return SignStatus_SIGN_STATUS_UNSPECIFIED
}

func (x *ContractServiceSignResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ContractServiceSignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\x02pb\"\xbf\x01\n" +
	"\x11ContractFormField\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x1c\n" +
	"\bcheckbox\x18\x02 \x01(\bH\x00R\bcheckbox\x12)\n" +
	"\x05table\x18\x03 \x01(\v2\x11.pb.ContractTableH\x00R\x05table\x12B\n" +
	"\x0eurl_attachment\x18\x04 \x01(\v2\x19.pb.ContractUrlAttachmentH\x00R\rurlAttachmentB\a\n" +
	"\x05value\"l\n" +
	"\rContractTable\x121\n" +
	"\acolumns\x18\x01 \x03(\v2\x17.pb.ContractTableColumnR\acolumns\x12(\n" +
	"\x04rows\x18\x02 \x03(\v2\x14.pb.ContractTableRowR\x04rows\"=\n" +
	"\x15ContractUrlAttachment\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"w\n" +
	"\x13ContractTableColumn\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x01R\x05scale\x12(\n" +
	"\x05align\x18\x03 \x01(\x0e2\r.pb.TextAlignH\x00R\x05align\x88\x01\x01B\b\n" +
	"\x06_align\"(\n" +
	"\x10ContractTableRow\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"\x87\x02\n" +
	"\x1cContractServiceCreateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12D\n" +
	"\x06values\x18\x02 \x03(\v2,.pb.ContractServiceCreateRequest.ValuesEntryR\x06values\x12\x16\n" +
	"\x06idcard\x18\x03 \x01(\tR\x06idcard\x12\x16\n" +
	"\x06expire\x18\x04 \x01(\x03R\x06expire\x1aP\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.pb.ContractFormFieldR\x05value:\x028\x01\"H\n" +
	"\x1dContractServiceCreateResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"\xd5\x01\n" +
	"\x1aContractServiceSignRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x16\n" +
	"\x06idcard\x18\b \x01(\tR\x06idcard\"q\n" +
	"\x1bContractServiceSignResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.pb.SignStatusR\x06status\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*i\n" +
	"\tTextAlign\x12\x1a\n" +
	"\x16TEXT_ALIGN_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTEXT_ALIGN_LEFT\x10\x01\x12\x15\n" +
	"\x11TEXT_ALIGN_CENTER\x10\x02\x12\x14\n" +
	"\x10TEXT_ALIGN_RIGHT\x10\x03*X\n" +
	"\n" +
	"SignStatus\x12\x1b\n" +
	"\x17SIGN_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SIGN_STATUS_SUCCESS\x10\x01\x12\x14\n" +
	"\x10SIGN_STATUS_FAIL\x10\x022\xad\x01\n" +
	"\x0fContractService\x12O\n" +
	"\x06Create\x12 .pb.ContractServiceCreateRequest\x1a!.pb.ContractServiceCreateResponse\"\x00\x12I\n" +
	"\x04Sign\x12\x1e.pb.ContractServiceSignRequest\x1a\x1f.pb.ContractServiceSignResponse\"\x00B[\n" +
	"\x06com.pbB\rContractProtoP\x01Z\x1aauroraride.com/edocseal/pb\xa2\x02\x03PXX\xaa\x02\x02Pb\xca\x02\x02Pb\xe2\x02\x0ePb\\GPBMetadata\xea\x02\x02Pbb\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_contract_proto_goTypes = []any{
	(TextAlign)(0),                        // 0: pb.TextAlign
	(SignStatus)(0),                       // 1: pb.SignStatus
	(*ContractFormField)(nil),             // 2: pb.ContractFormField
	(*ContractTable)(nil),                 // 3: pb.ContractTable
	(*ContractUrlAttachment)(nil),         // 4: pb.ContractUrlAttachment
	(*ContractTableColumn)(nil),           // 5: pb.ContractTableColumn
	(*ContractTableRow)(nil),              // 6: pb.ContractTableRow
	(*ContractServiceCreateRequest)(nil),  // 7: pb.ContractServiceCreateRequest
	(*ContractServiceCreateResponse)(nil), // 8: pb.ContractServiceCreateResponse
	(*ContractServiceSignRequest)(nil),    // 9: pb.ContractServiceSignRequest
	(*ContractServiceSignResponse)(nil),   // 10: pb.ContractServiceSignResponse
	nil,                                   // 11: pb.ContractServiceCreateRequest.ValuesEntry
}
var file_contract_proto_depIdxs = []int32{
	3,  // 0: pb.ContractFormField.table:type_name -> pb.ContractTable
	4,  // 1: pb.ContractFormField.url_attachment:type_name -> pb.ContractUrlAttachment
	5,  // 2: pb.ContractTable.columns:type_name -> pb.ContractTableColumn
	6,  // 3: pb.ContractTable.rows:type_name -> pb.ContractTableRow
	0,  // 4: pb.ContractTableColumn.align:type_name -> pb.TextAlign
	11, // 5: pb.ContractServiceCreateRequest.values:type_name -> pb.ContractServiceCreateRequest.ValuesEntry
	1,  // 6: pb.ContractServiceSignResponse.status:type_name -> pb.SignStatus
	2,  // 7: pb.ContractServiceCreateRequest.ValuesEntry.value:type_name -> pb.ContractFormField
	7,  // 8: pb.ContractService.Create:input_type -> pb.ContractServiceCreateRequest
	9,  // 9: pb.ContractService.Sign:input_type -> pb.ContractServiceSignRequest
	8,  // 10: pb.ContractService.Create:output_type -> pb.ContractServiceCreateResponse
	10, // 11: pb.ContractService.Sign:output_type -> pb.ContractServiceSignResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	file_contract_proto_msgTypes[0].OneofWrappers = []any{
		(*ContractFormField_Text)(nil),
		(*ContractFormField_Checkbox)(nil),
		(*ContractFormField_Table)(nil),
		(*ContractFormField_UrlAttachment)(nil),
	}
	file_contract_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		EnumInfos:         file_contract_proto_enumTypes,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
