// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: enterprise.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 企业证书
type EnterpriseCertificateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`                           // 证书生成方式：SELF 自签、SNCA 陕西CA
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`                           // 序列号（十六进制）
	NotBefore     int64                  `protobuf:"varint,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`   // 生效时间（秒级时间戳）
	NotAfter      int64                  `protobuf:"varint,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`      // 到期时间（秒级时间戳）
	IssuerName    string                 `protobuf:"bytes,5,opt,name=issuer_name,json=issuerName,proto3" json:"issuer_name,omitempty"` // 颁发者通用名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseCertificateInfo) Reset() {
	*x = EnterpriseCertificateInfo{}
	mi := &file_enterprise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseCertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseCertificateInfo) ProtoMessage() {}

func (x *EnterpriseCertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseCertificateInfo.ProtoReflect.Descriptor instead.
func (*EnterpriseCertificateInfo) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{0}
}

func (x *EnterpriseCertificateInfo) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *EnterpriseCertificateInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *EnterpriseCertificateInfo) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *EnterpriseCertificateInfo) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *EnterpriseCertificateInfo) GetIssuerName() string {
	if x != nil {
		return x.IssuerName
	}
	return ""
}

// 签约企业
type Enterprise struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	CreditCode    string                       `protobuf:"bytes,1,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"` // 统一社会信用代码
	Name          string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 企业名称
	Province      string                       `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`                       // 省份
	City          string                       `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`                               // 城市
	PersonName    string                       `protobuf:"bytes,5,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"` // 代办人姓名，向陕西CA 申请证书时使用
	Phone         string                       `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                             // 代办人手机号，向陕西CA 申请证书时使用
	Idcard        string                       `protobuf:"bytes,7,opt,name=idcard,proto3" json:"idcard,omitempty"`                           // 代办人身份证号，向陕西CA 申请证书时使用
	IsDefault     bool                         `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`   // 是否为当前签约企业
	Seal          []byte                       `protobuf:"bytes,9,opt,name=seal,proto3" json:"seal,omitempty"`                               // 签章图片（PNG）
	Certificates  []*EnterpriseCertificateInfo `protobuf:"bytes,10,rep,name=certificates,proto3" json:"certificates,omitempty"`              // 企业证书
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enterprise) Reset() {
	*x = Enterprise{}
	mi := &file_enterprise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enterprise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enterprise) ProtoMessage() {}

func (x *Enterprise) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enterprise.ProtoReflect.Descriptor instead.
func (*Enterprise) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{1}
}

func (x *Enterprise) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

func (x *Enterprise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enterprise) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Enterprise) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Enterprise) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *Enterprise) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Enterprise) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

func (x *Enterprise) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Enterprise) GetSeal() []byte {
	if x != nil {
		return x.Seal
	}
	return nil
}

func (x *Enterprise) GetCertificates() []*EnterpriseCertificateInfo {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type EnterpriseListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseListRequest) Reset() {
	*x = EnterpriseListRequest{}
	mi := &file_enterprise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseListRequest) ProtoMessage() {}

func (x *EnterpriseListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseListRequest.ProtoReflect.Descriptor instead.
func (*EnterpriseListRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{2}
}

type EnterpriseListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Enterprise          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseListResponse) Reset() {
	*x = EnterpriseListResponse{}
	mi := &file_enterprise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseListResponse) ProtoMessage() {}

func (x *EnterpriseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseListResponse.ProtoReflect.Descriptor instead.
func (*EnterpriseListResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{3}
}

func (x *EnterpriseListResponse) GetItems() []*Enterprise {
	if x != nil {
		return x.Items
	}
	return nil
}

type EnterpriseSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditCode    string                 `protobuf:"bytes,1,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"` // 统一社会信用代码
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 企业名称
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`                       // 省份
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`                               // 城市
	PersonName    string                 `protobuf:"bytes,5,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"` // 代办人姓名
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                             // 代办人手机号
	Idcard        string                 `protobuf:"bytes,7,opt,name=idcard,proto3" json:"idcard,omitempty"`                           // 代办人身份证号
	Seal          []byte                 `protobuf:"bytes,8,opt,name=seal,proto3" json:"seal,omitempty"`                               // 签章图片（PNG），为空时保留原签章
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseSaveRequest) Reset() {
	*x = EnterpriseSaveRequest{}
	mi := &file_enterprise_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseSaveRequest) ProtoMessage() {}

func (x *EnterpriseSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseSaveRequest.ProtoReflect.Descriptor instead.
func (*EnterpriseSaveRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{4}
}

func (x *EnterpriseSaveRequest) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetSeal() []byte {
	if x != nil {
		return x.Seal
	}
	return nil
}

type EnterpriseCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditCode    string                 `protobuf:"bytes,1,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"` // 统一社会信用代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseCodeRequest) Reset() {
	*x = EnterpriseCodeRequest{}
	mi := &file_enterprise_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseCodeRequest) ProtoMessage() {}

func (x *EnterpriseCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseCodeRequest.ProtoReflect.Descriptor instead.
func (*EnterpriseCodeRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{5}
}

func (x *EnterpriseCodeRequest) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

type EnterpriseEmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseEmptyRequest) Reset() {
	*x = EnterpriseEmptyRequest{}
	mi := &file_enterprise_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseEmptyRequest) ProtoMessage() {}

func (x *EnterpriseEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseEmptyRequest.ProtoReflect.Descriptor instead.
func (*EnterpriseEmptyRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{6}
}

type EnterpriseEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseEmptyResponse) Reset() {
	*x = EnterpriseEmptyResponse{}
	mi := &file_enterprise_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseEmptyResponse) ProtoMessage() {}

func (x *EnterpriseEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseEmptyResponse.ProtoReflect.Descriptor instead.
func (*EnterpriseEmptyResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{7}
}

// 根证书信息
type RootCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`                       // 主题
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`                         // 序列号（十六进制）
	NotBefore     int64                  `protobuf:"varint,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"` // 生效时间（秒级时间戳）
	NotAfter      int64                  `protobuf:"varint,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`    // 到期时间（秒级时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootCertificateResponse) Reset() {
	*x = RootCertificateResponse{}
	mi := &file_enterprise_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCertificateResponse) ProtoMessage() {}

func (x *RootCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCertificateResponse.ProtoReflect.Descriptor instead.
func (*RootCertificateResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{8}
}

func (x *RootCertificateResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RootCertificateResponse) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RootCertificateResponse) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *RootCertificateResponse) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

var File_enterprise_proto protoreflect.FileDescriptor

const file_enterprise_proto_rawDesc = "" +
	"\n" +
	"\x10enterprise.proto\x12\x02pb\"\xa8\x01\n" +
	"\x19EnterpriseCertificateInfo\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"not_before\x18\x03 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x04 \x01(\x03R\bnotAfter\x12\x1f\n" +
	"\vissuer_name\x18\x05 \x01(\tR\n" +
	"issuerName\"\xb6\x02\n" +
	"\n" +
	"Enterprise\x12\x1f\n" +
	"\vcredit_code\x18\x01 \x01(\tR\n" +
	"creditCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1f\n" +
	"\vperson_name\x18\x05 \x01(\tR\n" +
	"personName\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06idcard\x18\a \x01(\tR\x06idcard\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\x12\x12\n" +
	"\x04seal\x18\t \x01(\fR\x04seal\x12A\n" +
	"\fcertificates\x18\n" +
	" \x03(\v2\x1d.pb.EnterpriseCertificateInfoR\fcertificates\"\x17\n" +
	"\x15EnterpriseListRequest\">\n" +
	"\x16EnterpriseListResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.pb.EnterpriseR\x05items\"\xdf\x01\n" +
	"\x15EnterpriseSaveRequest\x12\x1f\n" +
	"\vcredit_code\x18\x01 \x01(\tR\n" +
	"creditCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1f\n" +
	"\vperson_name\x18\x05 \x01(\tR\n" +
	"personName\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06idcard\x18\a \x01(\tR\x06idcard\x12\x12\n" +
	"\x04seal\x18\b \x01(\fR\x04seal\"8\n" +
	"\x15EnterpriseCodeRequest\x12\x1f\n" +
	"\vcredit_code\x18\x01 \x01(\tR\n" +
	"creditCode\"\x18\n" +
	"\x16EnterpriseEmptyRequest\"\x19\n" +
	"\x17EnterpriseEmptyResponse\"\x87\x01\n" +
	"\x17RootCertificateResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"not_before\x18\x03 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x04 \x01(\x03R\bnotAfter2\x98\x04\n" +
	"\x11EnterpriseService\x12?\n" +
	"\x04List\x12\x19.pb.EnterpriseListRequest\x1a\x1a.pb.EnterpriseListResponse\"\x00\x12@\n" +
	"\x04Save\x12\x19.pb.EnterpriseSaveRequest\x1a\x1b.pb.EnterpriseEmptyResponse\"\x00\x12B\n" +
	"\x06Delete\x12\x19.pb.EnterpriseCodeRequest\x1a\x1b.pb.EnterpriseEmptyResponse\"\x00\x12F\n" +
	"\n" +
	"SetDefault\x12\x19.pb.EnterpriseCodeRequest\x1a\x1b.pb.EnterpriseEmptyResponse\"\x00\x12N\n" +
	"\x12RevokeCertificates\x12\x19.pb.EnterpriseCodeRequest\x1a\x1b.pb.EnterpriseEmptyResponse\"\x00\x12L\n" +
	"\x0fRootCertificate\x12\x1a.pb.EnterpriseEmptyRequest\x1a\x1b.pb.RootCertificateResponse\"\x00\x12V\n" +
	"\x19RegenerateRootCertificate\x12\x1a.pb.EnterpriseEmptyRequest\x1a\x1b.pb.RootCertificateResponse\"\x00B\x1fZ\x1dauroraride.com/edocseal/pb;pbb\x06proto3"

var (
	file_enterprise_proto_rawDescOnce sync.Once
	file_enterprise_proto_rawDescData []byte
)

func file_enterprise_proto_rawDescGZIP() []byte {
	file_enterprise_proto_rawDescOnce.Do(func() {
		file_enterprise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enterprise_proto_rawDesc), len(file_enterprise_proto_rawDesc)))
	})
	return file_enterprise_proto_rawDescData
}

var file_enterprise_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_enterprise_proto_goTypes = []any{
	(*EnterpriseCertificateInfo)(nil), // 0: pb.EnterpriseCertificateInfo
	(*Enterprise)(nil),                // 1: pb.Enterprise
	(*EnterpriseListRequest)(nil),     // 2: pb.EnterpriseListRequest
	(*EnterpriseListResponse)(nil),    // 3: pb.EnterpriseListResponse
	(*EnterpriseSaveRequest)(nil),     // 4: pb.EnterpriseSaveRequest
	(*EnterpriseCodeRequest)(nil),     // 5: pb.EnterpriseCodeRequest
	(*EnterpriseEmptyRequest)(nil),    // 6: pb.EnterpriseEmptyRequest
	(*EnterpriseEmptyResponse)(nil),   // 7: pb.EnterpriseEmptyResponse
	(*RootCertificateResponse)(nil),   // 8: pb.RootCertificateResponse
}
var file_enterprise_proto_depIdxs = []int32{
	0, // 0: pb.Enterprise.certificates:type_name -> pb.EnterpriseCertificateInfo
	1, // 1: pb.EnterpriseListResponse.items:type_name -> pb.Enterprise
	2, // 2: pb.EnterpriseService.List:input_type -> pb.EnterpriseListRequest
	4, // 3: pb.EnterpriseService.Save:input_type -> pb.EnterpriseSaveRequest
	5, // 4: pb.EnterpriseService.Delete:input_type -> pb.EnterpriseCodeRequest
	5, // 5: pb.EnterpriseService.SetDefault:input_type -> pb.EnterpriseCodeRequest
	5, // 6: pb.EnterpriseService.RevokeCertificates:input_type -> pb.EnterpriseCodeRequest
	6, // 7: pb.EnterpriseService.RootCertificate:input_type -> pb.EnterpriseEmptyRequest
	6, // 8: pb.EnterpriseService.RegenerateRootCertificate:input_type -> pb.EnterpriseEmptyRequest
	3, // 9: pb.EnterpriseService.List:output_type -> pb.EnterpriseListResponse
	7, // 10: pb.EnterpriseService.Save:output_type -> pb.EnterpriseEmptyResponse
	7, // 11: pb.EnterpriseService.Delete:output_type -> pb.EnterpriseEmptyResponse
	7, // 12: pb.EnterpriseService.SetDefault:output_type -> pb.EnterpriseEmptyResponse
	7, // 13: pb.EnterpriseService.RevokeCertificates:output_type -> pb.EnterpriseEmptyResponse
	8, // 14: pb.EnterpriseService.RootCertificate:output_type -> pb.RootCertificateResponse
	8, // 15: pb.EnterpriseService.RegenerateRootCertificate:output_type -> pb.RootCertificateResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_enterprise_proto_init() }
func file_enterprise_proto_init() {
	if File_enterprise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enterprise_proto_rawDesc), len(file_enterprise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enterprise_proto_goTypes,
		DependencyIndexes: file_enterprise_proto_depIdxs,
		MessageInfos:      file_enterprise_proto_msgTypes,
	}.Build()
	File_enterprise_proto = out.File
	file_enterprise_proto_goTypes = nil
	file_enterprise_proto_depIdxs = nil
}
