// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: enterprise.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnterpriseService_List_FullMethodName                      = "/pb.EnterpriseService/List"
	EnterpriseService_Save_FullMethodName                      = "/pb.EnterpriseService/Save"
	EnterpriseService_Delete_FullMethodName                    = "/pb.EnterpriseService/Delete"
	EnterpriseService_SetDefault_FullMethodName                = "/pb.EnterpriseService/SetDefault"
	EnterpriseService_GenerateCertificates_FullMethodName      = "/pb.EnterpriseService/GenerateCertificates"
	EnterpriseService_RegenerateRootCertificate_FullMethodName = "/pb.EnterpriseService/RegenerateRootCertificate"
)

// EnterpriseServiceClient is the client API for EnterpriseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnterpriseServiceClient interface {
	// 签约企业列表
	List(ctx context.Context, in *EnterpriseListRequest, opts ...grpc.CallOption) (*EnterpriseListResponse, error)
	// 新增或更新签约企业
	Save(ctx context.Context, in *EnterpriseSaveRequest, opts ...grpc.CallOption) (*EnterpriseEmptyResponse, error)
	// 删除签约企业
	Delete(ctx context.Context, in *EnterpriseCodeRequest, opts ...grpc.CallOption) (*EnterpriseEmptyResponse, error)
	// 设为签约企业
	SetDefault(ctx context.Context, in *EnterpriseCodeRequest, opts ...grpc.CallOption) (*EnterpriseEmptyResponse, error)
	// 按证书生成方式为缺少证书或证书已过期的企业生成企业证书，未过期的证书跳过
	GenerateCertificates(ctx context.Context, in *EnterpriseGenerateRequest, opts ...grpc.CallOption) (*EnterpriseGenerateResponse, error)
	// 重新生成企业自签根证书，该企业的自签证书随之作废；根证书未过期时拒绝
	RegenerateRootCertificate(ctx context.Context, in *EnterpriseCodeRequest, opts ...grpc.CallOption) (*EnterpriseEmptyResponse, error)
}

type enterpriseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnterpriseServiceClient(cc grpc.ClientConnInterface) EnterpriseServiceClient {
	return &enterpriseServiceClient{cc}
}

func (c *enterpriseServiceClient) List(ctx context.Context, in *EnterpriseListRequest, opts ...grpc.CallOption) (*EnterpriseListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterpriseListResponse)
	err := c.cc.Invoke(ctx, EnterpriseService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) Save(ctx context.Context, in *EnterpriseSaveRequest, opts ...grpc.CallOption) (*EnterpriseEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterpriseEmptyResponse)
	err := c.cc.Invoke(ctx, EnterpriseService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) Delete(ctx context.Context, in *EnterpriseCodeRequest, opts ...grpc.CallOption) (*EnterpriseEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterpriseEmptyResponse)
	err := c.cc.Invoke(ctx, EnterpriseService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) SetDefault(ctx context.Context, in *EnterpriseCodeRequest, opts ...grpc.CallOption) (*EnterpriseEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterpriseEmptyResponse)
	err := c.cc.Invoke(ctx, EnterpriseService_SetDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) GenerateCertificates(ctx context.Context, in *EnterpriseGenerateRequest, opts ...grpc.CallOption) (*EnterpriseGenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterpriseGenerateResponse)
	err := c.cc.Invoke(ctx, EnterpriseService_GenerateCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) RegenerateRootCertificate(ctx context.Context, in *EnterpriseCodeRequest, opts ...grpc.CallOption) (*EnterpriseEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterpriseEmptyResponse)
	err := c.cc.Invoke(ctx, EnterpriseService_RegenerateRootCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnterpriseServiceServer is the server API for EnterpriseService service.
// All implementations must embed UnimplementedEnterpriseServiceServer
// for forward compatibility.
type EnterpriseServiceServer interface {
	// 签约企业列表
	List(context.Context, *EnterpriseListRequest) (*EnterpriseListResponse, error)
	// 新增或更新签约企业
	Save(context.Context, *EnterpriseSaveRequest) (*EnterpriseEmptyResponse, error)
	// 删除签约企业
	Delete(context.Context, *EnterpriseCodeRequest) (*EnterpriseEmptyResponse, error)
	// 设为签约企业
	SetDefault(context.Context, *EnterpriseCodeRequest) (*EnterpriseEmptyResponse, error)
	// 按证书生成方式为缺少证书或证书已过期的企业生成企业证书，未过期的证书跳过
	GenerateCertificates(context.Context, *EnterpriseGenerateRequest) (*EnterpriseGenerateResponse, error)
	// 重新生成企业自签根证书，该企业的自签证书随之作废；根证书未过期时拒绝
	RegenerateRootCertificate(context.Context, *EnterpriseCodeRequest) (*EnterpriseEmptyResponse, error)
	mustEmbedUnimplementedEnterpriseServiceServer()
}

// UnimplementedEnterpriseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnterpriseServiceServer struct{}

func (UnimplementedEnterpriseServiceServer) List(context.Context, *EnterpriseListRequest) (*EnterpriseListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedEnterpriseServiceServer) Save(context.Context, *EnterpriseSaveRequest) (*EnterpriseEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedEnterpriseServiceServer) Delete(context.Context, *EnterpriseCodeRequest) (*EnterpriseEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEnterpriseServiceServer) SetDefault(context.Context, *EnterpriseCodeRequest) (*EnterpriseEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefault not implemented")
}
func (UnimplementedEnterpriseServiceServer) GenerateCertificates(context.Context, *EnterpriseGenerateRequest) (*EnterpriseGenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCertificates not implemented")
}
func (UnimplementedEnterpriseServiceServer) RegenerateRootCertificate(context.Context, *EnterpriseCodeRequest) (*EnterpriseEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegenerateRootCertificate not implemented")
}
func (UnimplementedEnterpriseServiceServer) mustEmbedUnimplementedEnterpriseServiceServer() {}
func (UnimplementedEnterpriseServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnterpriseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnterpriseServiceServer will
// result in compilation errors.
type UnsafeEnterpriseServiceServer interface {
	mustEmbedUnimplementedEnterpriseServiceServer()
}

func RegisterEnterpriseServiceServer(s grpc.ServiceRegistrar, srv EnterpriseServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnterpriseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnterpriseService_ServiceDesc, srv)
}

func _EnterpriseService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterpriseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).List(ctx, req.(*EnterpriseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterpriseSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).Save(ctx, req.(*EnterpriseSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterpriseCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).Delete(ctx, req.(*EnterpriseCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_SetDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterpriseCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).SetDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseService_SetDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).SetDefault(ctx, req.(*EnterpriseCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_GenerateCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterpriseGenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).GenerateCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseService_GenerateCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).GenerateCertificates(ctx, req.(*EnterpriseGenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_RegenerateRootCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterpriseCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).RegenerateRootCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseService_RegenerateRootCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).RegenerateRootCertificate(ctx, req.(*EnterpriseCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnterpriseService_ServiceDesc is the grpc.ServiceDesc for EnterpriseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnterpriseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EnterpriseService",
	HandlerType: (*EnterpriseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _EnterpriseService_List_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _EnterpriseService_Save_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EnterpriseService_Delete_Handler,
		},
		{
			MethodName: "SetDefault",
			Handler:    _EnterpriseService_SetDefault_Handler,
		},
		{
			MethodName: "GenerateCertificates",
			Handler:    _EnterpriseService_GenerateCertificates_Handler,
		},
		{
			MethodName: "RegenerateRootCertificate",
			Handler:    _EnterpriseService_RegenerateRootCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enterprise.proto",
}
