// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: enterprise.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 证书详情
type CertificateDetail struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Subject            string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`                                                 // 主题
	Issuer             string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`                                                   // 颁发者
	Serial             string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`                                                   // 序列号（十六进制）
	NotBefore          int64                  `protobuf:"varint,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`                           // 生效时间（秒级时间戳）
	NotAfter           int64                  `protobuf:"varint,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`                              // 到期时间（秒级时间戳）
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                                   // 状态：VALID 有效、RENEWING 待续签、EXPIRED 已过期
	PublicKey          string                 `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                            // 公钥算法与长度
	SignatureAlgorithm string                 `protobuf:"bytes,8,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"` // 签名算法
	KeyUsage           []string               `protobuf:"bytes,9,rep,name=key_usage,json=keyUsage,proto3" json:"key_usage,omitempty"`                               // 密钥用法
	IsCa               bool                   `protobuf:"varint,10,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`                                         // 是否为 CA 证书
	Fingerprint        string                 `protobuf:"bytes,11,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                                        // SHA-256 指纹
	Pem                string                 `protobuf:"bytes,12,opt,name=pem,proto3" json:"pem,omitempty"`                                                        // 证书 PEM 内容
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CertificateDetail) Reset() {
	*x = CertificateDetail{}
	mi := &file_enterprise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateDetail) ProtoMessage() {}

func (x *CertificateDetail) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateDetail.ProtoReflect.Descriptor instead.
func (*CertificateDetail) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateDetail) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CertificateDetail) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CertificateDetail) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *CertificateDetail) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *CertificateDetail) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *CertificateDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CertificateDetail) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CertificateDetail) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *CertificateDetail) GetKeyUsage() []string {
	if x != nil {
		return x.KeyUsage
	}
	return nil
}

func (x *CertificateDetail) GetIsCa() bool {
	if x != nil {
		return x.IsCa
	}
	return false
}

func (x *CertificateDetail) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *CertificateDetail) GetPem() string {
	if x != nil {
		return x.Pem
	}
	return ""
}

// 企业证书
type EnterpriseCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"` // 证书生成方式：SELF 自签、SNCA 陕西CA
	Detail        *CertificateDetail     `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // 证书详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseCertificate) Reset() {
	*x = EnterpriseCertificate{}
	mi := &file_enterprise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseCertificate) ProtoMessage() {}

func (x *EnterpriseCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseCertificate.ProtoReflect.Descriptor instead.
func (*EnterpriseCertificate) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{1}
}

func (x *EnterpriseCertificate) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *EnterpriseCertificate) GetDetail() *CertificateDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// 签约企业
type Enterprise struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	CreditCode      string                   `protobuf:"bytes,1,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"`                 // 统一社会信用代码
	Name            string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                               // 企业名称
	Province        string                   `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`                                       // 省份
	City            string                   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`                                               // 城市
	PersonName      string                   `protobuf:"bytes,5,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`                 // 代办人姓名，向陕西CA 申请证书时使用
	Phone           string                   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                                             // 代办人手机号，向陕西CA 申请证书时使用
	Idcard          string                   `protobuf:"bytes,7,opt,name=idcard,proto3" json:"idcard,omitempty"`                                           // 代办人身份证号，向陕西CA 申请证书时使用
	IsDefault       bool                     `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`                   // 是否为当前签约企业
	Seal            []byte                   `protobuf:"bytes,9,opt,name=seal,proto3" json:"seal,omitempty"`                                               // 签章图片（PNG）
	RootCertificate *CertificateDetail       `protobuf:"bytes,10,opt,name=root_certificate,json=rootCertificate,proto3" json:"root_certificate,omitempty"` // 自签根证书
	Certificates    []*EnterpriseCertificate `protobuf:"bytes,11,rep,name=certificates,proto3" json:"certificates,omitempty"`                              // 企业证书
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Enterprise) Reset() {
	*x = Enterprise{}
	mi := &file_enterprise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enterprise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enterprise) ProtoMessage() {}

func (x *Enterprise) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enterprise.ProtoReflect.Descriptor instead.
func (*Enterprise) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{2}
}

func (x *Enterprise) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

func (x *Enterprise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enterprise) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Enterprise) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Enterprise) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *Enterprise) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Enterprise) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

func (x *Enterprise) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Enterprise) GetSeal() []byte {
	if x != nil {
		return x.Seal
	}
	return nil
}

func (x *Enterprise) GetRootCertificate() *CertificateDetail {
	if x != nil {
		return x.RootCertificate
	}
	return nil
}

func (x *Enterprise) GetCertificates() []*EnterpriseCertificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type EnterpriseListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseListRequest) Reset() {
	*x = EnterpriseListRequest{}
	mi := &file_enterprise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseListRequest) ProtoMessage() {}

func (x *EnterpriseListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseListRequest.ProtoReflect.Descriptor instead.
func (*EnterpriseListRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{3}
}

type EnterpriseListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Enterprise          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseListResponse) Reset() {
	*x = EnterpriseListResponse{}
	mi := &file_enterprise_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseListResponse) ProtoMessage() {}

func (x *EnterpriseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseListResponse.ProtoReflect.Descriptor instead.
func (*EnterpriseListResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{4}
}

func (x *EnterpriseListResponse) GetItems() []*Enterprise {
	if x != nil {
		return x.Items
	}
	return nil
}

type EnterpriseSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditCode    string                 `protobuf:"bytes,1,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"` // 统一社会信用代码
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 企业名称
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`                       // 省份
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`                               // 城市
	PersonName    string                 `protobuf:"bytes,5,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"` // 代办人姓名
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                             // 代办人手机号
	Idcard        string                 `protobuf:"bytes,7,opt,name=idcard,proto3" json:"idcard,omitempty"`                           // 代办人身份证号
	Seal          []byte                 `protobuf:"bytes,8,opt,name=seal,proto3" json:"seal,omitempty"`                               // 签章图片（PNG），为空时保留原签章
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseSaveRequest) Reset() {
	*x = EnterpriseSaveRequest{}
	mi := &file_enterprise_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseSaveRequest) ProtoMessage() {}

func (x *EnterpriseSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseSaveRequest.ProtoReflect.Descriptor instead.
func (*EnterpriseSaveRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{5}
}

func (x *EnterpriseSaveRequest) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetIdcard() string {
	if x != nil {
		return x.Idcard
	}
	return ""
}

func (x *EnterpriseSaveRequest) GetSeal() []byte {
	if x != nil {
		return x.Seal
	}
	return nil
}

type EnterpriseCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditCode    string                 `protobuf:"bytes,1,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"` // 统一社会信用代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseCodeRequest) Reset() {
	*x = EnterpriseCodeRequest{}
	mi := &file_enterprise_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseCodeRequest) ProtoMessage() {}

func (x *EnterpriseCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseCodeRequest.ProtoReflect.Descriptor instead.
func (*EnterpriseCodeRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{6}
}

func (x *EnterpriseCodeRequest) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

type EnterpriseEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseEmptyResponse) Reset() {
	*x = EnterpriseEmptyResponse{}
	mi := &file_enterprise_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseEmptyResponse) ProtoMessage() {}

func (x *EnterpriseEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseEmptyResponse.ProtoReflect.Descriptor instead.
func (*EnterpriseEmptyResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{7}
}

type EnterpriseGenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"` // 证书生成方式：SELF 自签、SNCA 陕西CA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseGenerateRequest) Reset() {
	*x = EnterpriseGenerateRequest{}
	mi := &file_enterprise_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseGenerateRequest) ProtoMessage() {}

func (x *EnterpriseGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseGenerateRequest.ProtoReflect.Descriptor instead.
func (*EnterpriseGenerateRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{8}
}

func (x *EnterpriseGenerateRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// 企业证书生成结果
type EnterpriseGenerateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditCode    string                 `protobuf:"bytes,1,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"` // 统一社会信用代码
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 企业名称
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                           // 结果：GENERATED 已生成、EXISTS 证书未过期无需生成、FAILED 生成失败
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                         // 失败原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseGenerateResult) Reset() {
	*x = EnterpriseGenerateResult{}
	mi := &file_enterprise_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseGenerateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseGenerateResult) ProtoMessage() {}

func (x *EnterpriseGenerateResult) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseGenerateResult.ProtoReflect.Descriptor instead.
func (*EnterpriseGenerateResult) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{9}
}

func (x *EnterpriseGenerateResult) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

func (x *EnterpriseGenerateResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnterpriseGenerateResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EnterpriseGenerateResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnterpriseGenerateResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*EnterpriseGenerateResult `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseGenerateResponse) Reset() {
	*x = EnterpriseGenerateResponse{}
	mi := &file_enterprise_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseGenerateResponse) ProtoMessage() {}

func (x *EnterpriseGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseGenerateResponse.ProtoReflect.Descriptor instead.
func (*EnterpriseGenerateResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{10}
}

func (x *EnterpriseGenerateResponse) GetItems() []*EnterpriseGenerateResult {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_enterprise_proto protoreflect.FileDescriptor

const file_enterprise_proto_rawDesc = "" +
	"\n" +
	"\x10enterprise.proto\x12\x02pb\"\xe7\x02\n" +
	"\x11CertificateDetail\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"not_before\x18\x04 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x05 \x01(\x03R\bnotAfter\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"public_key\x18\a \x01(\tR\tpublicKey\x12/\n" +
	"\x13signature_algorithm\x18\b \x01(\tR\x12signatureAlgorithm\x12\x1b\n" +
	"\tkey_usage\x18\t \x03(\tR\bkeyUsage\x12\x13\n" +
	"\x05is_ca\x18\n" +
	" \x01(\bR\x04isCa\x12 \n" +
	"\vfingerprint\x18\v \x01(\tR\vfingerprint\x12\x10\n" +
	"\x03pem\x18\f \x01(\tR\x03pem\"^\n" +
	"\x15EnterpriseCertificate\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12-\n" +
	"\x06detail\x18\x02 \x01(\v2\x15.pb.CertificateDetailR\x06detail\"\xf4\x02\n" +
	"\n" +
	"Enterprise\x12\x1f\n" +
	"\vcredit_code\x18\x01 \x01(\tR\n" +
	"creditCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1f\n" +
	"\vperson_name\x18\x05 \x01(\tR\n" +
	"personName\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06idcard\x18\a \x01(\tR\x06idcard\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\x12\x12\n" +
	"\x04seal\x18\t \x01(\fR\x04seal\x12@\n" +
	"\x10root_certificate\x18\n" +
	" \x01(\v2\x15.pb.CertificateDetailR\x0frootCertificate\x12=\n" +
	"\fcertificates\x18\v \x03(\v2\x19.pb.EnterpriseCertificateR\fcertificates\"\x17\n" +
	"\x15EnterpriseListRequest\">\n" +
	"\x16EnterpriseListResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.pb.EnterpriseR\x05items\"\xdf\x01\n" +
	"\x15EnterpriseSaveRequest\x12\x1f\n" +
	"\vcredit_code\x18\x01 \x01(\tR\n" +
	"creditCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1f\n" +
	"\vperson_name\x18\x05 \x01(\tR\n" +
	"personName\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06idcard\x18\a \x01(\tR\x06idcard\x12\x12\n" +
	"\x04seal\x18\b \x01(\fR\x04seal\"8\n" +
	"\x15EnterpriseCodeRequest\x12\x1f\n" +
	"\vcredit_code\x18\x01 \x01(\tR\n" +
	"creditCode\"\x19\n" +
	"\x17EnterpriseEmptyResponse\"3\n" +
	"\x19EnterpriseGenerateRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"\x81\x01\n" +
	"\x18EnterpriseGenerateResult\x12\x1f\n" +
	"\vcredit_code\x18\x01 \x01(\tR\n" +
	"creditCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"P\n" +
	"\x1aEnterpriseGenerateResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.pb.EnterpriseGenerateResultR\x05items2\xd2\x03\n" +
	"\x11EnterpriseService\x12?\n" +
	"\x04List\x12\x19.pb.EnterpriseListRequest\x1a\x1a.pb.EnterpriseListResponse\"\x00\x12@\n" +
	"\x04Save\x12\x19.pb.EnterpriseSaveRequest\x1a\x1b.pb.EnterpriseEmptyResponse\"\x00\x12B\n" +
	"\x06Delete\x12\x19.pb.EnterpriseCodeRequest\x1a\x1b.pb.EnterpriseEmptyResponse\"\x00\x12F\n" +
	"\n" +
	"SetDefault\x12\x19.pb.EnterpriseCodeRequest\x1a\x1b.pb.EnterpriseEmptyResponse\"\x00\x12W\n" +
	"\x14GenerateCertificates\x12\x1d.pb.EnterpriseGenerateRequest\x1a\x1e.pb.EnterpriseGenerateResponse\"\x00\x12U\n" +
	"\x19RegenerateRootCertificate\x12\x19.pb.EnterpriseCodeRequest\x1a\x1b.pb.EnterpriseEmptyResponse\"\x00B\x1fZ\x1dauroraride.com/edocseal/pb;pbb\x06proto3"

var (
	file_enterprise_proto_rawDescOnce sync.Once
	file_enterprise_proto_rawDescData []byte
)

func file_enterprise_proto_rawDescGZIP() []byte {
	file_enterprise_proto_rawDescOnce.Do(func() {
		file_enterprise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enterprise_proto_rawDesc), len(file_enterprise_proto_rawDesc)))
	})
	return file_enterprise_proto_rawDescData
}

var file_enterprise_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_enterprise_proto_goTypes = []any{
	(*CertificateDetail)(nil),          // 0: pb.CertificateDetail
	(*EnterpriseCertificate)(nil),      // 1: pb.EnterpriseCertificate
	(*Enterprise)(nil),                 // 2: pb.Enterprise
	(*EnterpriseListRequest)(nil),      // 3: pb.EnterpriseListRequest
	(*EnterpriseListResponse)(nil),     // 4: pb.EnterpriseListResponse
	(*EnterpriseSaveRequest)(nil),      // 5: pb.EnterpriseSaveRequest
	(*EnterpriseCodeRequest)(nil),      // 6: pb.EnterpriseCodeRequest
	(*EnterpriseEmptyResponse)(nil),    // 7: pb.EnterpriseEmptyResponse
	(*EnterpriseGenerateRequest)(nil),  // 8: pb.EnterpriseGenerateRequest
	(*EnterpriseGenerateResult)(nil),   // 9: pb.EnterpriseGenerateResult
	(*EnterpriseGenerateResponse)(nil), // 10: pb.EnterpriseGenerateResponse
}
var file_enterprise_proto_depIdxs = []int32{
	0,  // 0: pb.EnterpriseCertificate.detail:type_name -> pb.CertificateDetail
	0,  // 1: pb.Enterprise.root_certificate:type_name -> pb.CertificateDetail
	1,  // 2: pb.Enterprise.certificates:type_name -> pb.EnterpriseCertificate
	2,  // 3: pb.EnterpriseListResponse.items:type_name -> pb.Enterprise
	9,  // 4: pb.EnterpriseGenerateResponse.items:type_name -> pb.EnterpriseGenerateResult
	3,  // 5: pb.EnterpriseService.List:input_type -> pb.EnterpriseListRequest
	5,  // 6: pb.EnterpriseService.Save:input_type -> pb.EnterpriseSaveRequest
	6,  // 7: pb.EnterpriseService.Delete:input_type -> pb.EnterpriseCodeRequest
	6,  // 8: pb.EnterpriseService.SetDefault:input_type -> pb.EnterpriseCodeRequest
	8,  // 9: pb.EnterpriseService.GenerateCertificates:input_type -> pb.EnterpriseGenerateRequest
	6,  // 10: pb.EnterpriseService.RegenerateRootCertificate:input_type -> pb.EnterpriseCodeRequest
	4,  // 11: pb.EnterpriseService.List:output_type -> pb.EnterpriseListResponse
	7,  // 12: pb.EnterpriseService.Save:output_type -> pb.EnterpriseEmptyResponse
	7,  // 13: pb.EnterpriseService.Delete:output_type -> pb.EnterpriseEmptyResponse
	7,  // 14: pb.EnterpriseService.SetDefault:output_type -> pb.EnterpriseEmptyResponse
	10, // 15: pb.EnterpriseService.GenerateCertificates:output_type -> pb.EnterpriseGenerateResponse
	7,  // 16: pb.EnterpriseService.RegenerateRootCertificate:output_type -> pb.EnterpriseEmptyResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_enterprise_proto_init() }
func file_enterprise_proto_init() {
	if File_enterprise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enterprise_proto_rawDesc), len(file_enterprise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enterprise_proto_goTypes,
		DependencyIndexes: file_enterprise_proto_depIdxs,
		MessageInfos:      file_enterprise_proto_msgTypes,
	}.Build()
	File_enterprise_proto = out.File
	file_enterprise_proto_goTypes = nil
	file_enterprise_proto_depIdxs = nil
}
